// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: boards.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const addPinToBoard = `-- name: AddPinToBoard :exec
INSERT INTO board_pins (board_id, pin_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddPinToBoardParams struct {
	BoardID uuid.UUID
	PinID   uuid.UUID
}

func (q *Queries) AddPinToBoard(ctx context.Context, arg AddPinToBoardParams) error {
	_, err := q.db.ExecContext(ctx, addPinToBoard, arg.BoardID, arg.PinID)
	return err
}

const countBoardPins = `-- name: CountBoardPins :one
SELECT count(*) FROM board_pins
WHERE board_id = $1
`

func (q *Queries) CountBoardPins(ctx context.Context, boardID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBoardPins, boardID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (creator_id, name, description, is_public)
VALUES ($1, $2, $3, $4)
RETURNING id, creator_id, name, description, is_public, created_at, updated_at
`

type CreateBoardParams struct {
	CreatorID   uuid.UUID
	Name        string
	Description sql.NullString
	IsPublic    bool
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error) {
	row := q.db.QueryRowContext(ctx, createBoard,
		arg.CreatorID,
		arg.Name,
		arg.Description,
		arg.IsPublic,
	)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBoard = `-- name: DeleteBoard :execrows
DELETE FROM boards
WHERE id = $1 AND creator_id = $2
`

type DeleteBoardParams struct {
	ID        uuid.UUID
	CreatorID uuid.UUID
}

func (q *Queries) DeleteBoard(ctx context.Context, arg DeleteBoardParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteBoard, arg.ID, arg.CreatorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBoard = `-- name: GetBoard :one
SELECT id, creator_id, name, description, is_public, created_at, updated_at FROM boards
WHERE id = $1
`

func (q *Queries) GetBoard(ctx context.Context, id uuid.UUID) (Board, error) {
	row := q.db.QueryRowContext(ctx, getBoard, id)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBoardPinImages = `-- name: ListBoardPinImages :many
SELECT p.og_image FROM board_pins bp
JOIN pins p ON p.id = bp.pin_id
WHERE bp.board_id = $1
  AND p.og_image IS NOT NULL
ORDER BY bp.created_at DESC
LIMIT 4
`

func (q *Queries) ListBoardPinImages(ctx context.Context, boardID uuid.UUID) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, listBoardPinImages, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var og_image sql.NullString
		if err := rows.Scan(&og_image); err != nil {
			return nil, err
		}
		items = append(items, og_image)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoardPins = `-- name: ListBoardPins :many
SELECT
    p.id, p.creator_id, p.url, p.title, p.description,
    p.field, p.tags, p.og_image, p.og_data, p.pin_count, p.created_at,
    c.id AS creator_id_ref,
    c.nickname AS creator_nickname,
    c.avatar_url AS creator_avatar_url
FROM board_pins bp
JOIN pins p ON p.id = bp.pin_id
JOIN creators c ON c.id = p.creator_id
WHERE bp.board_id = $1
ORDER BY bp.created_at DESC
LIMIT $2 OFFSET $3
`

type ListBoardPinsParams struct {
	BoardID uuid.UUID
	Limit   int32
	Offset  int32
}

type ListBoardPinsRow struct {
	ID               uuid.UUID
	CreatorID        uuid.UUID
	Url              string
	Title            string
	Description      sql.NullString
	Field            string
	Tags             []string
	OgImage          sql.NullString
	OgData           pqtype.NullRawMessage
	PinCount         int32
	CreatedAt        time.Time
	CreatorIDRef     uuid.UUID
	CreatorNickname  string
	CreatorAvatarUrl sql.NullString
}

func (q *Queries) ListBoardPins(ctx context.Context, arg ListBoardPinsParams) ([]ListBoardPinsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBoardPins, arg.BoardID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBoardPinsRow
	for rows.Next() {
		var i ListBoardPinsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.Field,
			pq.Array(&i.Tags),
			&i.OgImage,
			&i.OgData,
			&i.PinCount,
			&i.CreatedAt,
			&i.CreatorIDRef,
			&i.CreatorNickname,
			&i.CreatorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoardsByCreator = `-- name: ListBoardsByCreator :many
SELECT id, creator_id, name, description, is_public, created_at, updated_at FROM boards
WHERE creator_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListBoardsByCreator(ctx context.Context, creatorID uuid.UUID) ([]Board, error) {
	rows, err := q.db.QueryContext(ctx, listBoardsByCreator, creatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Board
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Name,
			&i.Description,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicBoardsByCreator = `-- name: ListPublicBoardsByCreator :many
SELECT id, creator_id, name, description, is_public, created_at, updated_at FROM boards
WHERE creator_id = $1 AND is_public = true
ORDER BY updated_at DESC
`

func (q *Queries) ListPublicBoardsByCreator(ctx context.Context, creatorID uuid.UUID) ([]Board, error) {
	rows, err := q.db.QueryContext(ctx, listPublicBoardsByCreator, creatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Board
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Name,
			&i.Description,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePinFromBoard = `-- name: RemovePinFromBoard :execrows
DELETE FROM board_pins
WHERE board_id = $1 AND pin_id = $2
`

type RemovePinFromBoardParams struct {
	BoardID uuid.UUID
	PinID   uuid.UUID
}

func (q *Queries) RemovePinFromBoard(ctx context.Context, arg RemovePinFromBoardParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removePinFromBoard, arg.BoardID, arg.PinID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateBoard = `-- name: UpdateBoard :one
UPDATE boards
SET name = $3,
    description = $4,
    is_public = $5,
    updated_at = now()
WHERE id = $1 AND creator_id = $2
RETURNING id, creator_id, name, description, is_public, created_at, updated_at
`

type UpdateBoardParams struct {
	ID          uuid.UUID
	CreatorID   uuid.UUID
	Name        string
	Description sql.NullString
	IsPublic    bool
}

func (q *Queries) UpdateBoard(ctx context.Context, arg UpdateBoardParams) (Board, error) {
	row := q.db.QueryRowContext(ctx, updateBoard,
		arg.ID,
		arg.CreatorID,
		arg.Name,
		arg.Description,
		arg.IsPublic,
	)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
