// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bot.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createEdge = `-- name: CreateEdge :exec
INSERT INTO bot_graph_edges (from_node_id, to_node_id)
VALUES ($1, $2)
ON CONFLICT (from_node_id, to_node_id) DO NOTHING
`

type CreateEdgeParams struct {
	FromNodeID uuid.UUID
	ToNodeID   uuid.UUID
}

// Bot Graph Edges queries
func (q *Queries) CreateEdge(ctx context.Context, arg CreateEdgeParams) error {
	_, err := q.db.ExecContext(ctx, createEdge, arg.FromNodeID, arg.ToNodeID)
	return err
}

const createNode = `-- name: CreateNode :one
INSERT INTO bot_graph_nodes (site_id, url, url_hash, node_type, script_id, sample_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, site_id, url, url_hash, node_type, script_id, created_at, updated_at, sample_url
`

type CreateNodeParams struct {
	SiteID    uuid.UUID
	Url       string
	UrlHash   string
	NodeType  sql.NullString
	ScriptID  uuid.NullUUID
	SampleUrl sql.NullString
}

// Bot Graph Nodes queries
func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (BotGraphNode, error) {
	row := q.db.QueryRowContext(ctx, createNode,
		arg.SiteID,
		arg.Url,
		arg.UrlHash,
		arg.NodeType,
		arg.ScriptID,
		arg.SampleUrl,
	)
	var i BotGraphNode
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Url,
		&i.UrlHash,
		&i.NodeType,
		&i.ScriptID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SampleUrl,
	)
	return i, err
}

const createScript = `-- name: CreateScript :one
INSERT INTO bot_scripts (site_id, node_type, script_lang, script_code, ai_model)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (site_id, node_type) DO UPDATE
SET script_code = EXCLUDED.script_code,
    ai_model = EXCLUDED.ai_model,
    updated_at = now()
RETURNING id, site_id, node_type, script_lang, script_code, ai_model, created_at, updated_at
`

type CreateScriptParams struct {
	SiteID     uuid.UUID
	NodeType   string
	ScriptLang sql.NullString
	ScriptCode string
	AiModel    sql.NullString
}

// Bot Scripts queries
func (q *Queries) CreateScript(ctx context.Context, arg CreateScriptParams) (BotScript, error) {
	row := q.db.QueryRowContext(ctx, createScript,
		arg.SiteID,
		arg.NodeType,
		arg.ScriptLang,
		arg.ScriptCode,
		arg.AiModel,
	)
	var i BotScript
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.NodeType,
		&i.ScriptLang,
		&i.ScriptCode,
		&i.AiModel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSite = `-- name: CreateSite :one
INSERT INTO bot_sites (domain, root_url)
VALUES ($1, $2)
RETURNING id, domain, root_url, active, created_at, updated_at
`

type CreateSiteParams struct {
	Domain  string
	RootUrl string
}

// Bot Sites queries
func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (BotSite, error) {
	row := q.db.QueryRowContext(ctx, createSite, arg.Domain, arg.RootUrl)
	var i BotSite
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.RootUrl,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEdgesByIDs = `-- name: DeleteEdgesByIDs :exec
DELETE FROM bot_graph_edges WHERE id = ANY($1::uuid[])
`

func (q *Queries) DeleteEdgesByIDs(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEdgesByIDs, pq.Array(dollar_1))
	return err
}

const deleteNodesByIDs = `-- name: DeleteNodesByIDs :exec
DELETE FROM bot_graph_nodes WHERE id = ANY($1::uuid[])
`

func (q *Queries) DeleteNodesByIDs(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteNodesByIDs, pq.Array(dollar_1))
	return err
}

const deleteSelfLoopEdges = `-- name: DeleteSelfLoopEdges :exec
DELETE FROM bot_graph_edges WHERE from_node_id = to_node_id
`

func (q *Queries) DeleteSelfLoopEdges(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteSelfLoopEdges)
	return err
}

const getEdgesByNode = `-- name: GetEdgesByNode :many
SELECT id, from_node_id, to_node_id, created_at FROM bot_graph_edges
WHERE from_node_id = $1
`

func (q *Queries) GetEdgesByNode(ctx context.Context, fromNodeID uuid.UUID) ([]BotGraphEdge, error) {
	rows, err := q.db.QueryContext(ctx, getEdgesByNode, fromNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotGraphEdge
	for rows.Next() {
		var i BotGraphEdge
		if err := rows.Scan(
			&i.ID,
			&i.FromNodeID,
			&i.ToNodeID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNodeByHash = `-- name: GetNodeByHash :one
SELECT id, site_id, url, url_hash, node_type, script_id, created_at, updated_at, sample_url FROM bot_graph_nodes
WHERE site_id = $1 AND url_hash = $2
`

type GetNodeByHashParams struct {
	SiteID  uuid.UUID
	UrlHash string
}

func (q *Queries) GetNodeByHash(ctx context.Context, arg GetNodeByHashParams) (BotGraphNode, error) {
	row := q.db.QueryRowContext(ctx, getNodeByHash, arg.SiteID, arg.UrlHash)
	var i BotGraphNode
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Url,
		&i.UrlHash,
		&i.NodeType,
		&i.ScriptID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SampleUrl,
	)
	return i, err
}

const getNodeByURL = `-- name: GetNodeByURL :one
SELECT id, site_id, url, url_hash, node_type, script_id, created_at, updated_at, sample_url FROM bot_graph_nodes
WHERE site_id = $1 AND url = $2
`

type GetNodeByURLParams struct {
	SiteID uuid.UUID
	Url    string
}

func (q *Queries) GetNodeByURL(ctx context.Context, arg GetNodeByURLParams) (BotGraphNode, error) {
	row := q.db.QueryRowContext(ctx, getNodeByURL, arg.SiteID, arg.Url)
	var i BotGraphNode
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Url,
		&i.UrlHash,
		&i.NodeType,
		&i.ScriptID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SampleUrl,
	)
	return i, err
}

const getScriptBySiteType = `-- name: GetScriptBySiteType :one
SELECT id, site_id, node_type, script_lang, script_code, ai_model, created_at, updated_at FROM bot_scripts
WHERE site_id = $1 AND node_type = $2
`

type GetScriptBySiteTypeParams struct {
	SiteID   uuid.UUID
	NodeType string
}

func (q *Queries) GetScriptBySiteType(ctx context.Context, arg GetScriptBySiteTypeParams) (BotScript, error) {
	row := q.db.QueryRowContext(ctx, getScriptBySiteType, arg.SiteID, arg.NodeType)
	var i BotScript
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.NodeType,
		&i.ScriptLang,
		&i.ScriptCode,
		&i.AiModel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSite = `-- name: GetSite :one
SELECT id, domain, root_url, active, created_at, updated_at FROM bot_sites
WHERE id = $1
`

func (q *Queries) GetSite(ctx context.Context, id uuid.UUID) (BotSite, error) {
	row := q.db.QueryRowContext(ctx, getSite, id)
	var i BotSite
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.RootUrl,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteByDomain = `-- name: GetSiteByDomain :one
SELECT id, domain, root_url, active, created_at, updated_at FROM bot_sites
WHERE domain = $1
`

func (q *Queries) GetSiteByDomain(ctx context.Context, domain string) (BotSite, error) {
	row := q.db.QueryRowContext(ctx, getSiteByDomain, domain)
	var i BotSite
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.RootUrl,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveSites = `-- name: ListActiveSites :many
SELECT id, domain, root_url, active, created_at, updated_at FROM bot_sites
WHERE active = true
ORDER BY created_at
`

func (q *Queries) ListActiveSites(ctx context.Context) ([]BotSite, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotSite
	for rows.Next() {
		var i BotSite
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.RootUrl,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllEdgesForGraph = `-- name: ListAllEdgesForGraph :many
SELECT id, from_node_id, to_node_id, created_at
FROM bot_graph_edges
ORDER BY created_at
`

func (q *Queries) ListAllEdgesForGraph(ctx context.Context) ([]BotGraphEdge, error) {
	rows, err := q.db.QueryContext(ctx, listAllEdgesForGraph)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotGraphEdge
	for rows.Next() {
		var i BotGraphEdge
		if err := rows.Scan(
			&i.ID,
			&i.FromNodeID,
			&i.ToNodeID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllNodesForGraph = `-- name: ListAllNodesForGraph :many
SELECT id, site_id, url, node_type, sample_url, created_at
FROM bot_graph_nodes
ORDER BY site_id, created_at
`

type ListAllNodesForGraphRow struct {
	ID        uuid.UUID
	SiteID    uuid.UUID
	Url       string
	NodeType  sql.NullString
	SampleUrl sql.NullString
	CreatedAt time.Time
}

func (q *Queries) ListAllNodesForGraph(ctx context.Context) ([]ListAllNodesForGraphRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllNodesForGraph)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllNodesForGraphRow
	for rows.Next() {
		var i ListAllNodesForGraphRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Url,
			&i.NodeType,
			&i.SampleUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSitesForGraph = `-- name: ListAllSitesForGraph :many
SELECT id, domain, root_url, active, created_at
FROM bot_sites
ORDER BY domain
`

type ListAllSitesForGraphRow struct {
	ID        uuid.UUID
	Domain    string
	RootUrl   string
	Active    bool
	CreatedAt time.Time
}

// Graph Visualization queries
func (q *Queries) ListAllSitesForGraph(ctx context.Context) ([]ListAllSitesForGraphRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllSitesForGraph)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllSitesForGraphRow
	for rows.Next() {
		var i ListAllSitesForGraphRow
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.RootUrl,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTags = `-- name: ListAllTags :many
SELECT id, name FROM tags
`

type ListAllTagsRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) ListAllTags(ctx context.Context) ([]ListAllTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllTagsRow
	for rows.Next() {
		var i ListAllTagsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEdgesBySiteNodes = `-- name: ListEdgesBySiteNodes :many
SELECT e.id, e.from_node_id, e.to_node_id
FROM bot_graph_edges e
JOIN bot_graph_nodes n ON e.from_node_id = n.id
WHERE n.site_id = $1
`

type ListEdgesBySiteNodesRow struct {
	ID         uuid.UUID
	FromNodeID uuid.UUID
	ToNodeID   uuid.UUID
}

func (q *Queries) ListEdgesBySiteNodes(ctx context.Context, siteID uuid.UUID) ([]ListEdgesBySiteNodesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEdgesBySiteNodes, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEdgesBySiteNodesRow
	for rows.Next() {
		var i ListEdgesBySiteNodesRow
		if err := rows.Scan(&i.ID, &i.FromNodeID, &i.ToNodeID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEdgesReferencingNodes = `-- name: ListEdgesReferencingNodes :many
SELECT id, from_node_id, to_node_id
FROM bot_graph_edges
WHERE from_node_id = ANY($1::uuid[]) OR to_node_id = ANY($1::uuid[])
`

type ListEdgesReferencingNodesRow struct {
	ID         uuid.UUID
	FromNodeID uuid.UUID
	ToNodeID   uuid.UUID
}

func (q *Queries) ListEdgesReferencingNodes(ctx context.Context, dollar_1 []uuid.UUID) ([]ListEdgesReferencingNodesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEdgesReferencingNodes, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEdgesReferencingNodesRow
	for rows.Next() {
		var i ListEdgesReferencingNodesRow
		if err := rows.Scan(&i.ID, &i.FromNodeID, &i.ToNodeID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeURLsBySite = `-- name: ListNodeURLsBySite :many
SELECT id, url, created_at
FROM bot_graph_nodes
WHERE site_id = $1
ORDER BY created_at
`

type ListNodeURLsBySiteRow struct {
	ID        uuid.UUID
	Url       string
	CreatedAt time.Time
}

func (q *Queries) ListNodeURLsBySite(ctx context.Context, siteID uuid.UUID) ([]ListNodeURLsBySiteRow, error) {
	rows, err := q.db.QueryContext(ctx, listNodeURLsBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNodeURLsBySiteRow
	for rows.Next() {
		var i ListNodeURLsBySiteRow
		if err := rows.Scan(&i.ID, &i.Url, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesBySite = `-- name: ListNodesBySite :many
SELECT id, site_id, url, url_hash, node_type, script_id, created_at, updated_at, sample_url FROM bot_graph_nodes
WHERE site_id = $1
ORDER BY created_at
`

func (q *Queries) ListNodesBySite(ctx context.Context, siteID uuid.UUID) ([]BotGraphNode, error) {
	rows, err := q.db.QueryContext(ctx, listNodesBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotGraphNode
	for rows.Next() {
		var i BotGraphNode
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Url,
			&i.UrlHash,
			&i.NodeType,
			&i.ScriptID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SampleUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesByType = `-- name: ListNodesByType :many
SELECT id, site_id, url, url_hash, node_type, script_id, created_at, updated_at, sample_url FROM bot_graph_nodes
WHERE site_id = $1 AND node_type = $2
ORDER BY created_at
`

type ListNodesByTypeParams struct {
	SiteID   uuid.UUID
	NodeType sql.NullString
}

func (q *Queries) ListNodesByType(ctx context.Context, arg ListNodesByTypeParams) ([]BotGraphNode, error) {
	rows, err := q.db.QueryContext(ctx, listNodesByType, arg.SiteID, arg.NodeType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotGraphNode
	for rows.Next() {
		var i BotGraphNode
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Url,
			&i.UrlHash,
			&i.NodeType,
			&i.ScriptID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SampleUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pinURLExists = `-- name: PinURLExists :one
SELECT EXISTS(SELECT 1 FROM pins WHERE url = $1) AS url_exists
`

func (q *Queries) PinURLExists(ctx context.Context, url sql.NullString) (bool, error) {
	row := q.db.QueryRowContext(ctx, pinURLExists, url)
	var url_exists bool
	err := row.Scan(&url_exists)
	return url_exists, err
}

const updateNodeScript = `-- name: UpdateNodeScript :exec
UPDATE bot_graph_nodes
SET script_id = $2, updated_at = now()
WHERE id = $1
`

type UpdateNodeScriptParams struct {
	ID       uuid.UUID
	ScriptID uuid.NullUUID
}

func (q *Queries) UpdateNodeScript(ctx context.Context, arg UpdateNodeScriptParams) error {
	_, err := q.db.ExecContext(ctx, updateNodeScript, arg.ID, arg.ScriptID)
	return err
}

const updateNodeURLAndHash = `-- name: UpdateNodeURLAndHash :exec
UPDATE bot_graph_nodes
SET url = $2, url_hash = $3, updated_at = now()
WHERE id = $1
`

type UpdateNodeURLAndHashParams struct {
	ID      uuid.UUID
	Url     string
	UrlHash string
}

func (q *Queries) UpdateNodeURLAndHash(ctx context.Context, arg UpdateNodeURLAndHashParams) error {
	_, err := q.db.ExecContext(ctx, updateNodeURLAndHash, arg.ID, arg.Url, arg.UrlHash)
	return err
}
