// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bot.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const createBotSource = `-- name: CreateBotSource :one
INSERT INTO bot_sources (name, platform, seed_urls, interval_hours, enabled)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, platform, seed_urls, interval_hours, enabled, last_crawled_at, stats, created_at
`

type CreateBotSourceParams struct {
	Name          string
	Platform      string
	SeedUrls      []string
	IntervalHours int32
	Enabled       bool
}

func (q *Queries) CreateBotSource(ctx context.Context, arg CreateBotSourceParams) (BotSource, error) {
	row := q.db.QueryRowContext(ctx, createBotSource,
		arg.Name,
		arg.Platform,
		pq.Array(arg.SeedUrls),
		arg.IntervalHours,
		arg.Enabled,
	)
	var i BotSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Platform,
		pq.Array(&i.SeedUrls),
		&i.IntervalHours,
		&i.Enabled,
		&i.LastCrawledAt,
		&i.Stats,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBotSource = `-- name: DeleteBotSource :execrows
DELETE FROM bot_sources
WHERE id = $1
`

func (q *Queries) DeleteBotSource(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteBotSource, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBotSource = `-- name: GetBotSource :one
SELECT id, name, platform, seed_urls, interval_hours, enabled, last_crawled_at, stats, created_at
FROM bot_sources
WHERE id = $1
`

func (q *Queries) GetBotSource(ctx context.Context, id uuid.UUID) (BotSource, error) {
	row := q.db.QueryRowContext(ctx, getBotSource, id)
	var i BotSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Platform,
		pq.Array(&i.SeedUrls),
		&i.IntervalHours,
		&i.Enabled,
		&i.LastCrawledAt,
		&i.Stats,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveBotSources = `-- name: ListActiveBotSources :many
SELECT id, name, platform, seed_urls, interval_hours, enabled, last_crawled_at, stats, created_at
FROM bot_sources
WHERE enabled = true
ORDER BY created_at
`

func (q *Queries) ListActiveBotSources(ctx context.Context) ([]BotSource, error) {
	rows, err := q.db.QueryContext(ctx, listActiveBotSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotSource
	for rows.Next() {
		var i BotSource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Platform,
			pq.Array(&i.SeedUrls),
			&i.IntervalHours,
			&i.Enabled,
			&i.LastCrawledAt,
			&i.Stats,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllBotSources = `-- name: ListAllBotSources :many
SELECT id, name, platform, seed_urls, interval_hours, enabled, last_crawled_at, stats, created_at
FROM bot_sources
ORDER BY created_at
`

func (q *Queries) ListAllBotSources(ctx context.Context) ([]BotSource, error) {
	rows, err := q.db.QueryContext(ctx, listAllBotSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotSource
	for rows.Next() {
		var i BotSource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Platform,
			pq.Array(&i.SeedUrls),
			&i.IntervalHours,
			&i.Enabled,
			&i.LastCrawledAt,
			&i.Stats,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTags = `-- name: ListAllTags :many
SELECT id, name FROM tags
`

type ListAllTagsRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) ListAllTags(ctx context.Context) ([]ListAllTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllTagsRow
	for rows.Next() {
		var i ListAllTagsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pinURLExists = `-- name: PinURLExists :one
SELECT EXISTS(SELECT 1 FROM pins WHERE url = $1) AS url_exists
`

func (q *Queries) PinURLExists(ctx context.Context, url sql.NullString) (bool, error) {
	row := q.db.QueryRowContext(ctx, pinURLExists, url)
	var url_exists bool
	err := row.Scan(&url_exists)
	return url_exists, err
}

const toggleBotSource = `-- name: ToggleBotSource :one
UPDATE bot_sources
SET enabled = $2
WHERE id = $1
RETURNING id, name, platform, seed_urls, interval_hours, enabled, last_crawled_at, stats, created_at
`

type ToggleBotSourceParams struct {
	ID      uuid.UUID
	Enabled bool
}

func (q *Queries) ToggleBotSource(ctx context.Context, arg ToggleBotSourceParams) (BotSource, error) {
	row := q.db.QueryRowContext(ctx, toggleBotSource, arg.ID, arg.Enabled)
	var i BotSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Platform,
		pq.Array(&i.SeedUrls),
		&i.IntervalHours,
		&i.Enabled,
		&i.LastCrawledAt,
		&i.Stats,
		&i.CreatedAt,
	)
	return i, err
}

const updateBotSourceStats = `-- name: UpdateBotSourceStats :exec
UPDATE bot_sources
SET last_crawled_at = now(), stats = $2
WHERE id = $1
`

type UpdateBotSourceStatsParams struct {
	ID    uuid.UUID
	Stats pqtype.NullRawMessage
}

func (q *Queries) UpdateBotSourceStats(ctx context.Context, arg UpdateBotSourceStatsParams) error {
	_, err := q.db.ExecContext(ctx, updateBotSourceStats, arg.ID, arg.Stats)
	return err
}
