// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: creators.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countWorksByCreator = `-- name: CountWorksByCreator :one
SELECT count(*) FROM works
WHERE creator_id = $1
`

func (q *Queries) CountWorksByCreator(ctx context.Context, creatorID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWorksByCreator, creatorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCreator = `-- name: CreateCreator :one
INSERT INTO creators (nickname, roles, contacts)
VALUES ($1, $2, $3)
RETURNING id, nickname, bio, roles, contacts, avatar_url, created_at, updated_at, email
`

type CreateCreatorParams struct {
	Nickname string
	Roles    []string
	Contacts json.RawMessage
}

func (q *Queries) CreateCreator(ctx context.Context, arg CreateCreatorParams) (Creator, error) {
	row := q.db.QueryRowContext(ctx, createCreator, arg.Nickname, pq.Array(arg.Roles), arg.Contacts)
	var i Creator
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.Bio,
		pq.Array(&i.Roles),
		&i.Contacts,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}

const createCreatorFromOAuth = `-- name: CreateCreatorFromOAuth :one
INSERT INTO creators (nickname, bio, roles, contacts, avatar_url, email)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, nickname, bio, roles, contacts, avatar_url, created_at, updated_at, email
`

type CreateCreatorFromOAuthParams struct {
	Nickname  string
	Bio       sql.NullString
	Roles     []string
	Contacts  json.RawMessage
	AvatarUrl sql.NullString
	Email     sql.NullString
}

func (q *Queries) CreateCreatorFromOAuth(ctx context.Context, arg CreateCreatorFromOAuthParams) (Creator, error) {
	row := q.db.QueryRowContext(ctx, createCreatorFromOAuth,
		arg.Nickname,
		arg.Bio,
		pq.Array(arg.Roles),
		arg.Contacts,
		arg.AvatarUrl,
		arg.Email,
	)
	var i Creator
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.Bio,
		pq.Array(&i.Roles),
		&i.Contacts,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}

const createCreatorFromOAuthOnConflict = `-- name: CreateCreatorFromOAuthOnConflict :one
INSERT INTO creators (nickname, bio, roles, contacts, avatar_url, email)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (email) DO NOTHING
RETURNING id, nickname, bio, roles, contacts, avatar_url, created_at, updated_at, email
`

type CreateCreatorFromOAuthOnConflictParams struct {
	Nickname  string
	Bio       sql.NullString
	Roles     []string
	Contacts  json.RawMessage
	AvatarUrl sql.NullString
	Email     sql.NullString
}

func (q *Queries) CreateCreatorFromOAuthOnConflict(ctx context.Context, arg CreateCreatorFromOAuthOnConflictParams) (Creator, error) {
	row := q.db.QueryRowContext(ctx, createCreatorFromOAuthOnConflict,
		arg.Nickname,
		arg.Bio,
		pq.Array(arg.Roles),
		arg.Contacts,
		arg.AvatarUrl,
		arg.Email,
	)
	var i Creator
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.Bio,
		pq.Array(&i.Roles),
		&i.Contacts,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}

const getCreator = `-- name: GetCreator :one
SELECT id, nickname, bio, roles, contacts, avatar_url, created_at, updated_at, email FROM creators
WHERE id = $1
`

func (q *Queries) GetCreator(ctx context.Context, id uuid.UUID) (Creator, error) {
	row := q.db.QueryRowContext(ctx, getCreator, id)
	var i Creator
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.Bio,
		pq.Array(&i.Roles),
		&i.Contacts,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}

const getCreatorByEmail = `-- name: GetCreatorByEmail :one
SELECT id, nickname, bio, roles, contacts, avatar_url, created_at, updated_at, email FROM creators
WHERE email = $1
`

func (q *Queries) GetCreatorByEmail(ctx context.Context, email sql.NullString) (Creator, error) {
	row := q.db.QueryRowContext(ctx, getCreatorByEmail, email)
	var i Creator
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.Bio,
		pq.Array(&i.Roles),
		&i.Contacts,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}

const getCreatorByEmailForUpdate = `-- name: GetCreatorByEmailForUpdate :one
SELECT id, nickname, bio, roles, contacts, avatar_url, created_at, updated_at, email FROM creators
WHERE email = $1
FOR UPDATE
`

func (q *Queries) GetCreatorByEmailForUpdate(ctx context.Context, email sql.NullString) (Creator, error) {
	row := q.db.QueryRowContext(ctx, getCreatorByEmailForUpdate, email)
	var i Creator
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.Bio,
		pq.Array(&i.Roles),
		&i.Contacts,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}

const listCreatorsByRoles = `-- name: ListCreatorsByRoles :many
SELECT id, nickname, bio, roles, contacts, avatar_url, created_at, updated_at, email FROM creators
WHERE roles && $1::text[]
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCreatorsByRolesParams struct {
	Column1 []string
	Limit   int32
	Offset  int32
}

func (q *Queries) ListCreatorsByRoles(ctx context.Context, arg ListCreatorsByRolesParams) ([]Creator, error) {
	rows, err := q.db.QueryContext(ctx, listCreatorsByRoles, pq.Array(arg.Column1), arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Creator
	for rows.Next() {
		var i Creator
		if err := rows.Scan(
			&i.ID,
			&i.Nickname,
			&i.Bio,
			pq.Array(&i.Roles),
			&i.Contacts,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCreator = `-- name: UpdateCreator :one
UPDATE creators
SET nickname = $2,
    bio = $3,
    roles = $4,
    contacts = $5,
    avatar_url = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, nickname, bio, roles, contacts, avatar_url, created_at, updated_at, email
`

type UpdateCreatorParams struct {
	ID        uuid.UUID
	Nickname  string
	Bio       sql.NullString
	Roles     []string
	Contacts  json.RawMessage
	AvatarUrl sql.NullString
}

func (q *Queries) UpdateCreator(ctx context.Context, arg UpdateCreatorParams) (Creator, error) {
	row := q.db.QueryRowContext(ctx, updateCreator,
		arg.ID,
		arg.Nickname,
		arg.Bio,
		pq.Array(arg.Roles),
		arg.Contacts,
		arg.AvatarUrl,
	)
	var i Creator
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.Bio,
		pq.Array(&i.Roles),
		&i.Contacts,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}
