// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: creators.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countPinsByCreator = `-- name: CountPinsByCreator :one
SELECT count(*) FROM pins
WHERE creator_id = $1
`

func (q *Queries) CountPinsByCreator(ctx context.Context, creatorID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPinsByCreator, creatorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCreatorFromOAuth = `-- name: CreateCreatorFromOAuth :one
INSERT INTO creators (nickname, avatar_url, email)
VALUES ($1, $2, $3)
RETURNING id, nickname, avatar_url, created_at, updated_at, email
`

type CreateCreatorFromOAuthParams struct {
	Nickname  string
	AvatarUrl sql.NullString
	Email     sql.NullString
}

func (q *Queries) CreateCreatorFromOAuth(ctx context.Context, arg CreateCreatorFromOAuthParams) (Creator, error) {
	row := q.db.QueryRowContext(ctx, createCreatorFromOAuth, arg.Nickname, arg.AvatarUrl, arg.Email)
	var i Creator
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}

const createCreatorFromOAuthOnConflict = `-- name: CreateCreatorFromOAuthOnConflict :one
INSERT INTO creators (nickname, avatar_url, email)
VALUES ($1, $2, $3)
ON CONFLICT (email) DO NOTHING
RETURNING id, nickname, avatar_url, created_at, updated_at, email
`

type CreateCreatorFromOAuthOnConflictParams struct {
	Nickname  string
	AvatarUrl sql.NullString
	Email     sql.NullString
}

func (q *Queries) CreateCreatorFromOAuthOnConflict(ctx context.Context, arg CreateCreatorFromOAuthOnConflictParams) (Creator, error) {
	row := q.db.QueryRowContext(ctx, createCreatorFromOAuthOnConflict, arg.Nickname, arg.AvatarUrl, arg.Email)
	var i Creator
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}

const getCreator = `-- name: GetCreator :one
SELECT id, nickname, avatar_url, created_at, updated_at, email FROM creators
WHERE id = $1
`

func (q *Queries) GetCreator(ctx context.Context, id uuid.UUID) (Creator, error) {
	row := q.db.QueryRowContext(ctx, getCreator, id)
	var i Creator
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}

const getCreatorByEmail = `-- name: GetCreatorByEmail :one
SELECT id, nickname, avatar_url, created_at, updated_at, email FROM creators
WHERE email = $1
`

func (q *Queries) GetCreatorByEmail(ctx context.Context, email sql.NullString) (Creator, error) {
	row := q.db.QueryRowContext(ctx, getCreatorByEmail, email)
	var i Creator
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}

const getCreatorByEmailForUpdate = `-- name: GetCreatorByEmailForUpdate :one
SELECT id, nickname, avatar_url, created_at, updated_at, email FROM creators
WHERE email = $1
FOR UPDATE
`

func (q *Queries) GetCreatorByEmailForUpdate(ctx context.Context, email sql.NullString) (Creator, error) {
	row := q.db.QueryRowContext(ctx, getCreatorByEmailForUpdate, email)
	var i Creator
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}

const updateCreator = `-- name: UpdateCreator :one
UPDATE creators
SET nickname = $2,
    avatar_url = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, nickname, avatar_url, created_at, updated_at, email
`

type UpdateCreatorParams struct {
	ID        uuid.UUID
	Nickname  string
	AvatarUrl sql.NullString
}

func (q *Queries) UpdateCreator(ctx context.Context, arg UpdateCreatorParams) (Creator, error) {
	row := q.db.QueryRowContext(ctx, updateCreator, arg.ID, arg.Nickname, arg.AvatarUrl)
	var i Creator
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}
