// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: frontier.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const claimHarvesterCandidates = `-- name: ClaimHarvesterCandidates :many
SELECT id, url, host
FROM harvester_frontier
WHERE harvested_at IS NULL
  AND harvest_error_count < 5
  AND next_harvest_at <= now()
ORDER BY score DESC, next_harvest_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type ClaimHarvesterCandidatesRow struct {
	ID   int64
	Url  string
	Host string
}

// Harvester counterpart of ClaimPioneerCandidates.
func (q *Queries) ClaimHarvesterCandidates(ctx context.Context, n int32) ([]ClaimHarvesterCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, claimHarvesterCandidates, n)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimHarvesterCandidatesRow
	for rows.Next() {
		var i ClaimHarvesterCandidatesRow
		if err := rows.Scan(&i.ID, &i.Url, &i.Host); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimPioneerCandidates = `-- name: ClaimPioneerCandidates :many
SELECT id, url, host
FROM pioneer_frontier
WHERE fetch_error_count < 5
  AND next_fetch_at <= now()
ORDER BY score DESC, next_fetch_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type ClaimPioneerCandidatesRow struct {
	ID   int64
	Url  string
	Host string
}

// Top-N claim candidates from the pioneer partial index. SKIP LOCKED ensures
// that two workers running the same query in parallel see disjoint rows.
// The outer transaction (opened by the Go caller) keeps the lock until
// mark_pioneer_in_flight or ROLLBACK; the claim protocol (scheduler-claim-api
// Decision: single transaction) forbids splitting SELECT and UPDATE.
func (q *Queries) ClaimPioneerCandidates(ctx context.Context, n int32) ([]ClaimPioneerCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, claimPioneerCandidates, n)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimPioneerCandidatesRow
	for rows.Next() {
		var i ClaimPioneerCandidatesRow
		if err := rows.Scan(&i.ID, &i.Url, &i.Host); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countHarvesterFrontier = `-- name: CountHarvesterFrontier :one
SELECT count(*) FROM harvester_frontier
`

// Placeholder query for scheduler-frontier-table change.
// Real claim/enqueue/fanout queries land in scheduler-claim-api.
func (q *Queries) CountHarvesterFrontier(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countHarvesterFrontier)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countHarvesterFrontierPins = `-- name: CountHarvesterFrontierPins :one
SELECT count(*) FROM harvester_frontier_pins
`

// Placeholder query for scheduler-frontier-table change.
// Real claim/enqueue/fanout queries land in scheduler-claim-api.
func (q *Queries) CountHarvesterFrontierPins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countHarvesterFrontierPins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPioneerFrontier = `-- name: CountPioneerFrontier :one
SELECT count(*) FROM pioneer_frontier
`

// Placeholder query for scheduler-frontier-table change.
// Real claim/enqueue/fanout queries land in scheduler-claim-api.
func (q *Queries) CountPioneerFrontier(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPioneerFrontier)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const enqueueHarvester = `-- name: EnqueueHarvester :exec
INSERT INTO harvester_frontier (normalized_url, url, url_hash, host, score)
SELECT
    UNNEST($1::text[]),
    UNNEST($2::text[]),
    UNNEST($3::bytea[]),
    UNNEST($4::text[]),
    0.0
ON CONFLICT (url_hash) DO UPDATE
SET next_harvest_at = now(),
    harvest_error_count = 0,
    last_updated_at = now()
WHERE harvester_frontier.harvested_at IS NULL
`

type EnqueueHarvesterParams struct {
	NormalizedUrls []string
	Urls           []string
	UrlHashes      [][]byte
	Hosts          []string
}

// Harvester enqueue. Conditional UPSERT per DECISIONS §8: re-enqueue of a
// URL that is still awaiting harvest (harvested_at IS NULL) resets the
// backoff schedule so the claim picks it up immediately; re-enqueue of an
// already-harvested URL is a no-op. snapshot_key is deliberately not set
// here — structured enqueue (harvester-scheduler-consumer) owns that.
func (q *Queries) EnqueueHarvester(ctx context.Context, arg EnqueueHarvesterParams) error {
	_, err := q.db.ExecContext(ctx, enqueueHarvester,
		pq.Array(arg.NormalizedUrls),
		pq.Array(arg.Urls),
		pq.Array(arg.UrlHashes),
		pq.Array(arg.Hosts),
	)
	return err
}

const enqueuePioneer = `-- name: EnqueuePioneer :exec

INSERT INTO pioneer_frontier (normalized_url, url, url_hash, host, depth, score)
SELECT
    UNNEST($1::text[]),
    UNNEST($2::text[]),
    UNNEST($3::bytea[]),
    UNNEST($4::text[]),
    0,
    0.0
ON CONFLICT (url_hash) DO NOTHING
`

type EnqueuePioneerParams struct {
	NormalizedUrls []string
	Urls           []string
	UrlHashes      [][]byte
	Hosts          []string
}

// scheduler-claim-api change:
// Enqueue / claim / status / record-error queries implementing the
// URLScheduler interface. Row lookup uses url_hash (sha256(normalized_url))
// exclusively because the BYTEA index is more selective than the TEXT
// normalized_url column.
// Pioneer enqueue. Batch upsert via UNNEST-parallel arrays. ON CONFLICT on
// url_hash keeps enqueue idempotent: a re-enqueue of a URL already in the
// frontier does not touch score, depth, or next_fetch_at. depth=0 and
// score=0.0 are spec-mandated defaults for URL-only Enqueue (proposal §
// Enqueue; structured enqueue lands in a future change).
func (q *Queries) EnqueuePioneer(ctx context.Context, arg EnqueuePioneerParams) error {
	_, err := q.db.ExecContext(ctx, enqueuePioneer,
		pq.Array(arg.NormalizedUrls),
		pq.Array(arg.Urls),
		pq.Array(arg.UrlHashes),
		pq.Array(arg.Hosts),
	)
	return err
}

const insertHarvesterFrontierPins = `-- name: InsertHarvesterFrontierPins :exec
INSERT INTO harvester_frontier_pins (frontier_id, pin_id)
SELECT $1, UNNEST($2::uuid[])
`

type InsertHarvesterFrontierPinsParams struct {
	FrontierID int64
	PinIds     []uuid.UUID
}

// Batch insert of (frontier_id, pin_id) pairs. pin_id is UUID — pins.id and
// harvester_frontier_pins.pin_id are both UUID (migration 000003, 000026).
func (q *Queries) InsertHarvesterFrontierPins(ctx context.Context, arg InsertHarvesterFrontierPinsParams) error {
	_, err := q.db.ExecContext(ctx, insertHarvesterFrontierPins, arg.FrontierID, pq.Array(arg.PinIds))
	return err
}

const markHarvesterInFlight = `-- name: MarkHarvesterInFlight :exec
UPDATE harvester_frontier
SET next_harvest_at = $1::timestamptz,
    last_updated_at = now()
WHERE id = $2
`

type MarkHarvesterInFlightParams struct {
	NextHarvestAt time.Time
	ID            int64
}

func (q *Queries) MarkHarvesterInFlight(ctx context.Context, arg MarkHarvesterInFlightParams) error {
	_, err := q.db.ExecContext(ctx, markHarvesterInFlight, arg.NextHarvestAt, arg.ID)
	return err
}

const markPioneerInFlight = `-- name: MarkPioneerInFlight :exec
UPDATE pioneer_frontier
SET next_fetch_at = $1::timestamptz,
    last_updated_at = now()
WHERE id = $2
`

type MarkPioneerInFlightParams struct {
	NextFetchAt time.Time
	ID          int64
}

// In-flight marker. next_fetch_at is passed in from Go (clock.Now() + lease)
// so tests can inject a fakeClock to simulate lease expiry without sleeping.
// No separate in_flight column; pushing next_fetch_at forward removes the
// row from the claim partial index, and an unclean worker crash will
// naturally restore visibility once the lease expires.
func (q *Queries) MarkPioneerInFlight(ctx context.Context, arg MarkPioneerInFlightParams) error {
	_, err := q.db.ExecContext(ctx, markPioneerInFlight, arg.NextFetchAt, arg.ID)
	return err
}

const setStatusFetchFailed = `-- name: SetStatusFetchFailed :execrows
UPDATE pioneer_frontier
SET last_updated_at = now()
WHERE url_hash = $1
`

// Failure marking only. Error-count bump and next_fetch_at backoff are
// RecordFetchError's responsibility (consumer contract: failure → both
// SetStatus + RecordFetchError are invoked).
func (q *Queries) SetStatusFetchFailed(ctx context.Context, urlHash []byte) (int64, error) {
	result, err := q.db.ExecContext(ctx, setStatusFetchFailed, urlHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setStatusFetched = `-- name: SetStatusFetched :execrows
UPDATE pioneer_frontier
SET last_fetched_at = now(),
    next_fetch_at = now() + interval '365 days',
    fetch_error_count = 0,
    last_updated_at = now()
WHERE url_hash = $1
`

// Pioneer success. 365-day re-crawl schedule per DECISIONS §8. Error count
// reset here rather than in a separate RecordFetchSuccess because success
// is reported via SetStatus per consumer contract.
func (q *Queries) SetStatusFetched(ctx context.Context, urlHash []byte) (int64, error) {
	result, err := q.db.ExecContext(ctx, setStatusFetched, urlHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setStatusHarvestFailed = `-- name: SetStatusHarvestFailed :execrows
UPDATE harvester_frontier
SET last_updated_at = now()
WHERE url_hash = $1
`

func (q *Queries) SetStatusHarvestFailed(ctx context.Context, urlHash []byte) (int64, error) {
	result, err := q.db.ExecContext(ctx, setStatusHarvestFailed, urlHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setStatusHarvested = `-- name: SetStatusHarvested :one
UPDATE harvester_frontier
SET harvested_at = now(),
    harvest_error_count = 0,
    last_updated_at = now()
WHERE url_hash = $1
RETURNING id
`

// Harvester success. Returns the frontier_id so the caller can insert the
// pin-id mapping in the same transaction.
func (q *Queries) SetStatusHarvested(ctx context.Context, urlHash []byte) (int64, error) {
	row := q.db.QueryRowContext(ctx, setStatusHarvested, urlHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateFetchErrorBackoff = `-- name: UpdateFetchErrorBackoff :execrows
UPDATE pioneer_frontier
SET fetch_error_count = LEAST(fetch_error_count + 1, 5),
    next_fetch_at = CASE LEAST(fetch_error_count + 1, 5)
        WHEN 1 THEN $1::timestamptz
        WHEN 2 THEN $2::timestamptz
        WHEN 3 THEN $3::timestamptz
        WHEN 4 THEN $4::timestamptz
        ELSE       $5::timestamptz
    END,
    last_updated_at = now()
WHERE url_hash = $6
`

type UpdateFetchErrorBackoffParams struct {
	NextAt1 time.Time
	NextAt2 time.Time
	NextAt3 time.Time
	NextAt4 time.Time
	NextAt5 time.Time
	UrlHash []byte
}

// Non-4xx path. Caller passes ts1..ts5 = T_report + delay(n) + jitter(n)
// for n = 1..5 (all pre-jittered in Go). LEAST(count+1, 5) keeps index
// lookup safe even if a race managed to bump count past 5 (not expected in
// practice because dead rows are excluded from claim). The LEAST expression
// is evaluated twice per UPDATE — once to set fetch_error_count, once as
// the CASE selector — on the same row snapshot, so both evaluations see the
// same fetch_error_count value (PostgreSQL single-statement semantics).
func (q *Queries) UpdateFetchErrorBackoff(ctx context.Context, arg UpdateFetchErrorBackoffParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateFetchErrorBackoff,
		arg.NextAt1,
		arg.NextAt2,
		arg.NextAt3,
		arg.NextAt4,
		arg.NextAt5,
		arg.UrlHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateFetchErrorDead = `-- name: UpdateFetchErrorDead :execrows

UPDATE pioneer_frontier
SET fetch_error_count = 5,
    last_updated_at = now()
WHERE url_hash = $1
`

// scheduler-retry-backoff change:
// Failure reporting queries. spec.md requires that the count increment and
// the next_*_at update be visible as a single atomic write (SHALL NOT tear
// across readers), so each RecordFetchError / RecordHarvestError is expressed
// as ONE UPDATE statement. The caller pre-computes five candidate
// T_report + delay(n) + jitter(n) timestamps (one per error_count_after
// ∈ {1..5}) and the CASE clause in the UPDATE picks the one matching the
// post-increment count. This keeps the jitter computation in Go (per design
// decision "공식 계산은 Go app, time.Now() 기준") while still writing both
// columns in a single statement.
// http_4xx path: set fetch_error_count to the dead threshold immediately.
// next_fetch_at is intentionally NOT updated; the row is excluded from the
// partial index (fetch_error_count < 5), so its backoff timestamp is unused.
// :execrows lets the caller detect an unknown key (rows affected = 0) and
// log a warning without synthesizing a row.
func (q *Queries) UpdateFetchErrorDead(ctx context.Context, urlHash []byte) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateFetchErrorDead, urlHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateHarvestErrorBackoff = `-- name: UpdateHarvestErrorBackoff :execrows
UPDATE harvester_frontier
SET harvest_error_count = LEAST(harvest_error_count + 1, 5),
    next_harvest_at = CASE LEAST(harvest_error_count + 1, 5)
        WHEN 1 THEN $1::timestamptz
        WHEN 2 THEN $2::timestamptz
        WHEN 3 THEN $3::timestamptz
        WHEN 4 THEN $4::timestamptz
        ELSE       $5::timestamptz
    END,
    last_updated_at = now()
WHERE url_hash = $6
`

type UpdateHarvestErrorBackoffParams struct {
	NextAt1 time.Time
	NextAt2 time.Time
	NextAt3 time.Time
	NextAt4 time.Time
	NextAt5 time.Time
	UrlHash []byte
}

// Harvester counterpart of UpdateFetchErrorBackoff. See that query for the
// LEAST-evaluated-twice semantics note.
func (q *Queries) UpdateHarvestErrorBackoff(ctx context.Context, arg UpdateHarvestErrorBackoffParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateHarvestErrorBackoff,
		arg.NextAt1,
		arg.NextAt2,
		arg.NextAt3,
		arg.NextAt4,
		arg.NextAt5,
		arg.UrlHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateHarvestErrorDead = `-- name: UpdateHarvestErrorDead :execrows
UPDATE harvester_frontier
SET harvest_error_count = 5,
    last_updated_at = now()
WHERE url_hash = $1
`

// http_4xx path for the harvester frontier.
func (q *Queries) UpdateHarvestErrorDead(ctx context.Context, urlHash []byte) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateHarvestErrorDead, urlHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertHarvesterWithSnapshot = `-- name: UpsertHarvesterWithSnapshot :exec
INSERT INTO harvester_frontier (normalized_url, url, url_hash, host, snapshot_key, score)
VALUES ($1, $2, $3, $4, $5, 0.0)
ON CONFLICT (url_hash) DO UPDATE
SET snapshot_key = EXCLUDED.snapshot_key,
    next_harvest_at = now(),
    harvest_error_count = 0,
    last_updated_at = now()
WHERE harvester_frontier.harvested_at IS NULL
`

type UpsertHarvesterWithSnapshotParams struct {
	NormalizedUrl string
	Url           string
	UrlHash       []byte
	Host          string
	SnapshotKey   sql.NullString
}

// pioneer-scheduler-consumer change: singular UPSERT used by Pioneer
// consumer's fanout-B path. Writes snapshot_key alongside the frontier row
// so Harvester can pick the exact snapshot to re-hydrate. Guarded by
// `WHERE harvester_frontier.harvested_at IS NULL` so an already-harvested
// row is a no-op (spec: scheduler EnqueueHarvester ADDED Requirement,
// "이미 harvest된 URL은 no-op"). For un-harvested rows snapshot_key is
// overwritten with EXCLUDED.snapshot_key (= caller's argument), and both
// next_harvest_at and harvest_error_count are reset so the row becomes
// immediately claimable.
func (q *Queries) UpsertHarvesterWithSnapshot(ctx context.Context, arg UpsertHarvesterWithSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, upsertHarvesterWithSnapshot,
		arg.NormalizedUrl,
		arg.Url,
		arg.UrlHash,
		arg.Host,
		arg.SnapshotKey,
	)
	return err
}
