// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: frontier.sql

package db

import (
	"context"
)

const countHarvesterFrontier = `-- name: CountHarvesterFrontier :one
SELECT count(*) FROM harvester_frontier
`

// Placeholder query for scheduler-frontier-table change.
// Real claim/enqueue/fanout queries land in scheduler-claim-api.
func (q *Queries) CountHarvesterFrontier(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countHarvesterFrontier)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countHarvesterFrontierPins = `-- name: CountHarvesterFrontierPins :one
SELECT count(*) FROM harvester_frontier_pins
`

// Placeholder query for scheduler-frontier-table change.
// Real claim/enqueue/fanout queries land in scheduler-claim-api.
func (q *Queries) CountHarvesterFrontierPins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countHarvesterFrontierPins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPioneerFrontier = `-- name: CountPioneerFrontier :one
SELECT count(*) FROM pioneer_frontier
`

// Placeholder query for scheduler-frontier-table change.
// Real claim/enqueue/fanout queries land in scheduler-claim-api.
func (q *Queries) CountPioneerFrontier(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPioneerFrontier)
	var count int64
	err := row.Scan(&count)
	return count, err
}
