// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: interactions.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const countUserPins = `-- name: CountUserPins :one
SELECT count(*) FROM pins
WHERE creator_id = $1
`

func (q *Queries) CountUserPins(ctx context.Context, creatorID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserPins, creatorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInteraction = `-- name: CreateInteraction :exec
INSERT INTO interactions (user_id, pin_id, type)
VALUES ($1, $2, $3)
`

type CreateInteractionParams struct {
	UserID uuid.UUID
	PinID  uuid.NullUUID
	Type   string
}

func (q *Queries) CreateInteraction(ctx context.Context, arg CreateInteractionParams) error {
	_, err := q.db.ExecContext(ctx, createInteraction, arg.UserID, arg.PinID, arg.Type)
	return err
}

const getUserMediaTypeFrequency = `-- name: GetUserMediaTypeFrequency :many
SELECT p.media_type, COUNT(*) AS freq
FROM pins p
WHERE p.creator_id = $1
GROUP BY p.media_type
ORDER BY freq DESC
LIMIT $2
`

type GetUserMediaTypeFrequencyParams struct {
	CreatorID uuid.UUID
	Limit     int32
}

type GetUserMediaTypeFrequencyRow struct {
	MediaType string
	Freq      int64
}

func (q *Queries) GetUserMediaTypeFrequency(ctx context.Context, arg GetUserMediaTypeFrequencyParams) ([]GetUserMediaTypeFrequencyRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserMediaTypeFrequency, arg.CreatorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserMediaTypeFrequencyRow
	for rows.Next() {
		var i GetUserMediaTypeFrequencyRow
		if err := rows.Scan(&i.MediaType, &i.Freq); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTagFrequency = `-- name: GetUserTagFrequency :many
SELECT pt.tag_id AS tag_id, COUNT(*) AS freq
FROM pins p
JOIN pin_tags pt ON pt.pin_id = p.id
WHERE p.creator_id = $1
GROUP BY pt.tag_id
ORDER BY freq DESC
LIMIT $2
`

type GetUserTagFrequencyParams struct {
	CreatorID uuid.UUID
	Limit     int32
}

type GetUserTagFrequencyRow struct {
	TagID uuid.UUID
	Freq  int64
}

func (q *Queries) GetUserTagFrequency(ctx context.Context, arg GetUserTagFrequencyParams) ([]GetUserTagFrequencyRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserTagFrequency, arg.CreatorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserTagFrequencyRow
	for rows.Next() {
		var i GetUserTagFrequencyRow
		if err := rows.Scan(&i.TagID, &i.Freq); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recommendByMediaType = `-- name: RecommendByMediaType :many
SELECT
    p.id, p.creator_id, p.media_url, p.media_type, p.url, p.title, p.description,
    p.og_image, p.og_data, p.created_at,
    c.id AS creator_id_ref,
    c.nickname AS creator_nickname,
    c.avatar_url AS creator_avatar_url
FROM pins p
JOIN creators c ON c.id = p.creator_id
WHERE p.media_type = ANY($1::text[])
  AND p.creator_id != $2
ORDER BY p.created_at DESC
LIMIT $3
`

type RecommendByMediaTypeParams struct {
	Column1   []string
	CreatorID uuid.UUID
	Limit     int32
}

type RecommendByMediaTypeRow struct {
	ID               uuid.UUID
	CreatorID        uuid.UUID
	MediaUrl         string
	MediaType        string
	Url              sql.NullString
	Title            string
	Description      sql.NullString
	OgImage          sql.NullString
	OgData           pqtype.NullRawMessage
	CreatedAt        time.Time
	CreatorIDRef     uuid.UUID
	CreatorNickname  string
	CreatorAvatarUrl sql.NullString
}

func (q *Queries) RecommendByMediaType(ctx context.Context, arg RecommendByMediaTypeParams) ([]RecommendByMediaTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, recommendByMediaType, pq.Array(arg.Column1), arg.CreatorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecommendByMediaTypeRow
	for rows.Next() {
		var i RecommendByMediaTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.MediaUrl,
			&i.MediaType,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.OgImage,
			&i.OgData,
			&i.CreatedAt,
			&i.CreatorIDRef,
			&i.CreatorNickname,
			&i.CreatorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recommendByTags = `-- name: RecommendByTags :many
SELECT
    p.id, p.creator_id, p.media_url, p.media_type, p.url, p.title, p.description,
    p.og_image, p.og_data, p.created_at,
    c.id AS creator_id_ref,
    c.nickname AS creator_nickname,
    c.avatar_url AS creator_avatar_url
FROM pins p
JOIN creators c ON c.id = p.creator_id
WHERE EXISTS (
    SELECT 1 FROM pin_tags pt WHERE pt.pin_id = p.id AND pt.tag_id = ANY($1::uuid[])
)
  AND p.creator_id != $2
ORDER BY
    (SELECT count(*) FROM pin_tags pt WHERE pt.pin_id = p.id AND pt.tag_id = ANY($1::uuid[])) DESC,
    p.created_at DESC
LIMIT $3
`

type RecommendByTagsParams struct {
	Column1   []uuid.UUID
	CreatorID uuid.UUID
	Limit     int32
}

type RecommendByTagsRow struct {
	ID               uuid.UUID
	CreatorID        uuid.UUID
	MediaUrl         string
	MediaType        string
	Url              sql.NullString
	Title            string
	Description      sql.NullString
	OgImage          sql.NullString
	OgData           pqtype.NullRawMessage
	CreatedAt        time.Time
	CreatorIDRef     uuid.UUID
	CreatorNickname  string
	CreatorAvatarUrl sql.NullString
}

func (q *Queries) RecommendByTags(ctx context.Context, arg RecommendByTagsParams) ([]RecommendByTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, recommendByTags, pq.Array(arg.Column1), arg.CreatorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecommendByTagsRow
	for rows.Next() {
		var i RecommendByTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.MediaUrl,
			&i.MediaType,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.OgImage,
			&i.OgData,
			&i.CreatedAt,
			&i.CreatorIDRef,
			&i.CreatorNickname,
			&i.CreatorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
