// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: interactions.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const countUserPins = `-- name: CountUserPins :one
SELECT count(*) FROM pins
WHERE creator_id = $1
`

func (q *Queries) CountUserPins(ctx context.Context, creatorID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserPins, creatorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInteraction = `-- name: CreateInteraction :exec
INSERT INTO interactions (user_id, pin_id, type)
VALUES ($1, $2, $3)
`

type CreateInteractionParams struct {
	UserID uuid.UUID
	PinID  uuid.NullUUID
	Type   string
}

func (q *Queries) CreateInteraction(ctx context.Context, arg CreateInteractionParams) error {
	_, err := q.db.ExecContext(ctx, createInteraction, arg.UserID, arg.PinID, arg.Type)
	return err
}

const getUserTagFrequency = `-- name: GetUserTagFrequency :many
SELECT unnest(p.tags) AS tag, COUNT(*) AS freq
FROM pins p
WHERE p.creator_id = $1
GROUP BY tag
ORDER BY freq DESC
LIMIT $2
`

type GetUserTagFrequencyParams struct {
	CreatorID uuid.UUID
	Limit     int32
}

type GetUserTagFrequencyRow struct {
	Tag  interface{}
	Freq int64
}

func (q *Queries) GetUserTagFrequency(ctx context.Context, arg GetUserTagFrequencyParams) ([]GetUserTagFrequencyRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserTagFrequency, arg.CreatorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserTagFrequencyRow
	for rows.Next() {
		var i GetUserTagFrequencyRow
		if err := rows.Scan(&i.Tag, &i.Freq); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recommendByTags = `-- name: RecommendByTags :many
SELECT
    p.id, p.creator_id, p.url, p.title, p.description,
    p.field, p.tags, p.og_image, p.og_data, p.pin_count, p.created_at,
    c.id AS creator_id_ref,
    c.nickname AS creator_nickname,
    c.avatar_url AS creator_avatar_url
FROM pins p
JOIN creators c ON c.id = p.creator_id
WHERE p.tags && $1::text[]
  AND p.creator_id != $2
ORDER BY array_length(p.tags & $1::text[], 1) DESC NULLS LAST, p.created_at DESC
LIMIT $3
`

type RecommendByTagsParams struct {
	Column1   []string
	CreatorID uuid.UUID
	Limit     int32
}

type RecommendByTagsRow struct {
	ID               uuid.UUID
	CreatorID        uuid.UUID
	Url              string
	Title            string
	Description      sql.NullString
	Field            string
	Tags             []string
	OgImage          sql.NullString
	OgData           pqtype.NullRawMessage
	PinCount         int32
	CreatedAt        time.Time
	CreatorIDRef     uuid.UUID
	CreatorNickname  string
	CreatorAvatarUrl sql.NullString
}

func (q *Queries) RecommendByTags(ctx context.Context, arg RecommendByTagsParams) ([]RecommendByTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, recommendByTags, pq.Array(arg.Column1), arg.CreatorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecommendByTagsRow
	for rows.Next() {
		var i RecommendByTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.Field,
			pq.Array(&i.Tags),
			&i.OgImage,
			&i.OgData,
			&i.PinCount,
			&i.CreatedAt,
			&i.CreatorIDRef,
			&i.CreatorNickname,
			&i.CreatorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
