// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AuthAccount struct {
	ID         uuid.UUID
	CreatorID  uuid.UUID
	Provider   string
	ProviderID string
	Email      sql.NullString
	CreatedAt  time.Time
	Profile    pqtype.NullRawMessage
}

type Board struct {
	ID          uuid.UUID
	CreatorID   uuid.UUID
	Name        string
	Description sql.NullString
	IsPublic    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type BoardPin struct {
	BoardID   uuid.UUID
	PinID     uuid.UUID
	CreatedAt time.Time
}

type BotGraphEdge struct {
	ID         uuid.UUID
	SiteID     uuid.UUID
	FromNodeID uuid.UUID
	ToNodeID   uuid.UUID
	LinkText   sql.NullString
	CreatedAt  time.Time
}

type BotGraphNode struct {
	ID            uuid.UUID
	SiteID        uuid.UUID
	Url           string
	UrlHash       string
	Depth         int32
	NodeType      sql.NullString
	ParentUrl     sql.NullString
	ScriptID      uuid.NullUUID
	VisitCount    sql.NullInt32
	SuccessCount  sql.NullInt32
	FailCount     sql.NullInt32
	LastVisitedAt sql.NullTime
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type BotHarvestRun struct {
	ID                uuid.UUID
	SiteID            uuid.UUID
	StartedAt         time.Time
	CompletedAt       sql.NullTime
	Status            string
	NodesVisited      sql.NullInt32
	NodesSucceeded    sql.NullInt32
	NodesFailed       sql.NullInt32
	ItemsExtracted    sql.NullInt32
	ItemsDeduplicated sql.NullInt32
	PinsCreated       sql.NullInt32
	ErrorMessage      sql.NullString
	CreatedAt         time.Time
}

type BotPioneerRun struct {
	ID               uuid.UUID
	SiteID           uuid.UUID
	StartedAt        time.Time
	CompletedAt      sql.NullTime
	Status           string
	NodesDiscovered  sql.NullInt32
	NodesUpdated     sql.NullInt32
	ScriptsGenerated sql.NullInt32
	ScriptsReused    sql.NullInt32
	AiApiCalls       sql.NullInt32
	AiCostUsd        sql.NullString
	ErrorMessage     sql.NullString
	CreatedAt        time.Time
}

type BotScript struct {
	ID                     uuid.UUID
	SiteID                 uuid.UUID
	NodeType               string
	ScriptLang             sql.NullString
	ScriptCode             string
	AiModel                sql.NullString
	GenerationCostUsd      sql.NullString
	ValidationSuccessCount sql.NullInt32
	ValidationFailCount    sql.NullInt32
	LastValidatedAt        sql.NullTime
	SuccessCount           sql.NullInt32
	FailCount              sql.NullInt32
	AvgExecutionMs         sql.NullInt32
	AvgItemsExtracted      sql.NullFloat64
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

type BotSite struct {
	ID                 uuid.UUID
	Domain             string
	RootUrl            string
	PioneerStatus      sql.NullString
	PioneerStartedAt   sql.NullTime
	PioneerCompletedAt sql.NullTime
	LastHarvestAt      sql.NullTime
	Active             sql.NullBool
	Metadata           pqtype.NullRawMessage
	CreatedAt          time.Time
}

type BotSource struct {
	ID            uuid.UUID
	Name          string
	Platform      string
	SeedUrls      []string
	IntervalHours int32
	Enabled       bool
	LastCrawledAt sql.NullTime
	Stats         pqtype.NullRawMessage
	CreatedAt     time.Time
}

type Creator struct {
	ID        uuid.UUID
	Nickname  string
	AvatarUrl sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     sql.NullString
}

type Interaction struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	PinID     uuid.NullUUID
	Type      string
	CreatedAt time.Time
}

type Pin struct {
	ID          uuid.UUID
	CreatorID   uuid.UUID
	Url         sql.NullString
	Title       string
	Description sql.NullString
	OgImage     sql.NullString
	OgData      pqtype.NullRawMessage
	CreatedAt   time.Time
	MediaUrl    string
	MediaType   string
}

type PinTag struct {
	PinID uuid.UUID
	TagID uuid.UUID
}

type Tag struct {
	ID           uuid.UUID
	Name         string
	Slug         string
	Category     string
	DisplayOrder sql.NullInt32
}
