// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AuthAccount struct {
	ID         uuid.UUID
	CreatorID  uuid.UUID
	Provider   string
	ProviderID string
	Email      sql.NullString
	CreatedAt  time.Time
	Profile    pqtype.NullRawMessage
}

type Board struct {
	ID          uuid.UUID
	CreatorID   uuid.UUID
	Name        string
	Description sql.NullString
	IsPublic    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type BoardPin struct {
	BoardID   uuid.UUID
	PinID     uuid.UUID
	CreatedAt time.Time
}

type BotGraphEdge struct {
	ID         uuid.UUID
	FromNodeID uuid.UUID
	ToNodeID   uuid.UUID
	CreatedAt  time.Time
}

type BotGraphNode struct {
	ID        uuid.UUID
	SiteID    uuid.UUID
	Url       string
	UrlHash   string
	NodeType  sql.NullString
	ScriptID  uuid.NullUUID
	CreatedAt time.Time
	UpdatedAt time.Time
	SampleUrl sql.NullString
}

type BotScript struct {
	ID         uuid.UUID
	SiteID     uuid.UUID
	NodeType   string
	ScriptLang sql.NullString
	ScriptCode string
	AiModel    sql.NullString
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type BotSite struct {
	ID        uuid.UUID
	Domain    string
	RootUrl   string
	Active    bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type BotSource struct {
	ID            uuid.UUID
	Name          string
	Platform      string
	SeedUrls      []string
	IntervalHours int32
	Enabled       bool
	LastCrawledAt sql.NullTime
	Stats         pqtype.NullRawMessage
	CreatedAt     time.Time
}

type Creator struct {
	ID        uuid.UUID
	Nickname  string
	AvatarUrl sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     sql.NullString
}

type HarvesterFrontier struct {
	ID                int64
	NormalizedUrl     string
	Url               string
	UrlHash           []byte
	Host              string
	SnapshotKey       sql.NullString
	Score             float64
	HarvestedAt       sql.NullTime
	NextHarvestAt     time.Time
	HarvestErrorCount int32
	LastUpdatedAt     time.Time
}

type HarvesterFrontierPin struct {
	FrontierID int64
	PinID      uuid.UUID
}

type Interaction struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	PinID     uuid.NullUUID
	Type      string
	CreatedAt time.Time
}

type Pin struct {
	ID          uuid.UUID
	CreatorID   uuid.UUID
	Url         sql.NullString
	Title       string
	Description sql.NullString
	OgImage     sql.NullString
	OgData      pqtype.NullRawMessage
	CreatedAt   time.Time
	MediaUrl    string
	MediaType   string
}

type PinTag struct {
	PinID uuid.UUID
	TagID uuid.UUID
}

type PioneerFrontier struct {
	ID              int64
	NormalizedUrl   string
	Url             string
	UrlHash         []byte
	Host            string
	Depth           int32
	Score           float64
	LastFetchedAt   sql.NullTime
	NextFetchAt     time.Time
	FetchErrorCount int32
	LastUpdatedAt   time.Time
}

type Tag struct {
	ID           uuid.UUID
	Name         string
	Slug         string
	Category     string
	DisplayOrder sql.NullInt32
}
