// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AuthAccount struct {
	ID         uuid.UUID
	CreatorID  uuid.UUID
	Provider   string
	ProviderID string
	Email      sql.NullString
	CreatedAt  time.Time
	Profile    pqtype.NullRawMessage
}

type Creator struct {
	ID        uuid.UUID
	Nickname  string
	Bio       sql.NullString
	Roles     []string
	Contacts  json.RawMessage
	AvatarUrl sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     sql.NullString
}

type Work struct {
	ID          uuid.UUID
	CreatorID   uuid.UUID
	Url         string
	Title       string
	Description sql.NullString
	Field       string
	Tags        []string
	OgImage     sql.NullString
	OgData      pqtype.NullRawMessage
	CreatedAt   time.Time
}
