// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pins.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const countPins = `-- name: CountPins :one
SELECT count(*) FROM pins p
WHERE ($1::varchar = '' OR p.media_type = $1)
  AND ($2::uuid[] IS NULL OR EXISTS (
    SELECT 1 FROM pin_tags pt WHERE pt.pin_id = p.id AND pt.tag_id = ANY($2::uuid[])
  ))
`

type CountPinsParams struct {
	Column1 string
	Column2 []uuid.UUID
}

func (q *Queries) CountPins(ctx context.Context, arg CountPinsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPins, arg.Column1, pq.Array(arg.Column2))
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPinsByCreatorFiltered = `-- name: CountPinsByCreatorFiltered :one
SELECT count(*) FROM pins p
WHERE p.creator_id = $1
  AND ($2::varchar = '' OR p.media_type = $2)
  AND ($3::uuid[] IS NULL OR EXISTS (
    SELECT 1 FROM pin_tags pt WHERE pt.pin_id = p.id AND pt.tag_id = ANY($3::uuid[])
  ))
`

type CountPinsByCreatorFilteredParams struct {
	CreatorID uuid.UUID
	Column2   string
	Column3   []uuid.UUID
}

func (q *Queries) CountPinsByCreatorFiltered(ctx context.Context, arg CountPinsByCreatorFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPinsByCreatorFiltered, arg.CreatorID, arg.Column2, pq.Array(arg.Column3))
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPin = `-- name: CreatePin :one
INSERT INTO pins (creator_id, media_url, media_type, url, title, description, og_image, og_data)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, creator_id, url, title, description, og_image, og_data, created_at, media_url, media_type
`

type CreatePinParams struct {
	CreatorID   uuid.UUID
	MediaUrl    string
	MediaType   string
	Url         sql.NullString
	Title       string
	Description sql.NullString
	OgImage     sql.NullString
	OgData      pqtype.NullRawMessage
}

func (q *Queries) CreatePin(ctx context.Context, arg CreatePinParams) (Pin, error) {
	row := q.db.QueryRowContext(ctx, createPin,
		arg.CreatorID,
		arg.MediaUrl,
		arg.MediaType,
		arg.Url,
		arg.Title,
		arg.Description,
		arg.OgImage,
		arg.OgData,
	)
	var i Pin
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.OgImage,
		&i.OgData,
		&i.CreatedAt,
		&i.MediaUrl,
		&i.MediaType,
	)
	return i, err
}

const deletePin = `-- name: DeletePin :execrows
DELETE FROM pins
WHERE id = $1 AND creator_id = $2
`

type DeletePinParams struct {
	ID        uuid.UUID
	CreatorID uuid.UUID
}

func (q *Queries) DeletePin(ctx context.Context, arg DeletePinParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePin, arg.ID, arg.CreatorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const fallbackRelatedByMediaType = `-- name: FallbackRelatedByMediaType :many
SELECT
    p.id, p.creator_id, p.media_url, p.media_type, p.url, p.title, p.description,
    p.og_image, p.og_data, p.created_at,
    c.id AS creator_id_ref,
    c.nickname AS creator_nickname,
    c.avatar_url AS creator_avatar_url
FROM pins p
JOIN creators c ON c.id = p.creator_id
WHERE p.media_type = $1
  AND p.id != ALL($2::uuid[])
ORDER BY p.created_at DESC
LIMIT $3
`

type FallbackRelatedByMediaTypeParams struct {
	MediaType string
	Column2   []uuid.UUID
	Limit     int32
}

type FallbackRelatedByMediaTypeRow struct {
	ID               uuid.UUID
	CreatorID        uuid.UUID
	MediaUrl         string
	MediaType        string
	Url              sql.NullString
	Title            string
	Description      sql.NullString
	OgImage          sql.NullString
	OgData           pqtype.NullRawMessage
	CreatedAt        time.Time
	CreatorIDRef     uuid.UUID
	CreatorNickname  string
	CreatorAvatarUrl sql.NullString
}

func (q *Queries) FallbackRelatedByMediaType(ctx context.Context, arg FallbackRelatedByMediaTypeParams) ([]FallbackRelatedByMediaTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, fallbackRelatedByMediaType, arg.MediaType, pq.Array(arg.Column2), arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FallbackRelatedByMediaTypeRow
	for rows.Next() {
		var i FallbackRelatedByMediaTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.MediaUrl,
			&i.MediaType,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.OgImage,
			&i.OgData,
			&i.CreatedAt,
			&i.CreatorIDRef,
			&i.CreatorNickname,
			&i.CreatorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fallbackRelatedLatest = `-- name: FallbackRelatedLatest :many
SELECT
    p.id, p.creator_id, p.media_url, p.media_type, p.url, p.title, p.description,
    p.og_image, p.og_data, p.created_at,
    c.id AS creator_id_ref,
    c.nickname AS creator_nickname,
    c.avatar_url AS creator_avatar_url
FROM pins p
JOIN creators c ON c.id = p.creator_id
WHERE p.id != ALL($1::uuid[])
ORDER BY p.created_at DESC
LIMIT $2
`

type FallbackRelatedLatestParams struct {
	Column1 []uuid.UUID
	Limit   int32
}

type FallbackRelatedLatestRow struct {
	ID               uuid.UUID
	CreatorID        uuid.UUID
	MediaUrl         string
	MediaType        string
	Url              sql.NullString
	Title            string
	Description      sql.NullString
	OgImage          sql.NullString
	OgData           pqtype.NullRawMessage
	CreatedAt        time.Time
	CreatorIDRef     uuid.UUID
	CreatorNickname  string
	CreatorAvatarUrl sql.NullString
}

func (q *Queries) FallbackRelatedLatest(ctx context.Context, arg FallbackRelatedLatestParams) ([]FallbackRelatedLatestRow, error) {
	rows, err := q.db.QueryContext(ctx, fallbackRelatedLatest, pq.Array(arg.Column1), arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FallbackRelatedLatestRow
	for rows.Next() {
		var i FallbackRelatedLatestRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.MediaUrl,
			&i.MediaType,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.OgImage,
			&i.OgData,
			&i.CreatedAt,
			&i.CreatorIDRef,
			&i.CreatorNickname,
			&i.CreatorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPin = `-- name: GetPin :one
SELECT id, creator_id, url, title, description, og_image, og_data, created_at, media_url, media_type FROM pins
WHERE id = $1
`

func (q *Queries) GetPin(ctx context.Context, id uuid.UUID) (Pin, error) {
	row := q.db.QueryRowContext(ctx, getPin, id)
	var i Pin
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.OgImage,
		&i.OgData,
		&i.CreatedAt,
		&i.MediaUrl,
		&i.MediaType,
	)
	return i, err
}

const getPinTags = `-- name: GetPinTags :many
SELECT t.id, t.name, t.slug, t.category
FROM pin_tags pt
JOIN tags t ON t.id = pt.tag_id
WHERE pt.pin_id = $1
ORDER BY t.category, t.display_order
`

type GetPinTagsRow struct {
	ID       uuid.UUID
	Name     string
	Slug     string
	Category string
}

func (q *Queries) GetPinTags(ctx context.Context, pinID uuid.UUID) ([]GetPinTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPinTags, pinID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPinTagsRow
	for rows.Next() {
		var i GetPinTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPinWithCreator = `-- name: GetPinWithCreator :one
SELECT
    p.id, p.creator_id, p.media_url, p.media_type, p.url, p.title, p.description,
    p.og_image, p.og_data, p.created_at,
    c.id AS creator_id_ref,
    c.nickname AS creator_nickname,
    c.avatar_url AS creator_avatar_url
FROM pins p
JOIN creators c ON c.id = p.creator_id
WHERE p.id = $1
`

type GetPinWithCreatorRow struct {
	ID               uuid.UUID
	CreatorID        uuid.UUID
	MediaUrl         string
	MediaType        string
	Url              sql.NullString
	Title            string
	Description      sql.NullString
	OgImage          sql.NullString
	OgData           pqtype.NullRawMessage
	CreatedAt        time.Time
	CreatorIDRef     uuid.UUID
	CreatorNickname  string
	CreatorAvatarUrl sql.NullString
}

func (q *Queries) GetPinWithCreator(ctx context.Context, id uuid.UUID) (GetPinWithCreatorRow, error) {
	row := q.db.QueryRowContext(ctx, getPinWithCreator, id)
	var i GetPinWithCreatorRow
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.MediaUrl,
		&i.MediaType,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.OgImage,
		&i.OgData,
		&i.CreatedAt,
		&i.CreatorIDRef,
		&i.CreatorNickname,
		&i.CreatorAvatarUrl,
	)
	return i, err
}

const linkPinTag = `-- name: LinkPinTag :exec
INSERT INTO pin_tags (pin_id, tag_id) VALUES ($1, $2)
`

type LinkPinTagParams struct {
	PinID uuid.UUID
	TagID uuid.UUID
}

func (q *Queries) LinkPinTag(ctx context.Context, arg LinkPinTagParams) error {
	_, err := q.db.ExecContext(ctx, linkPinTag, arg.PinID, arg.TagID)
	return err
}

const listLatestPinsWithCreator = `-- name: ListLatestPinsWithCreator :many
SELECT
    p.id, p.creator_id, p.media_url, p.media_type, p.url, p.title, p.description,
    p.og_image, p.og_data, p.created_at,
    c.id AS creator_id_ref,
    c.nickname AS creator_nickname,
    c.avatar_url AS creator_avatar_url
FROM pins p
JOIN creators c ON c.id = p.creator_id
WHERE ($1::varchar = '' OR p.media_type = $1)
  AND ($2::uuid[] IS NULL OR EXISTS (
    SELECT 1 FROM pin_tags pt WHERE pt.pin_id = p.id AND pt.tag_id = ANY($2::uuid[])
  ))
  AND (p.created_at < $3::timestamptz OR (p.created_at = $3::timestamptz AND p.id < $4::uuid))
ORDER BY p.created_at DESC, p.id DESC
LIMIT $5
`

type ListLatestPinsWithCreatorParams struct {
	Column1 string
	Column2 []uuid.UUID
	Column3 time.Time
	Column4 uuid.UUID
	Limit   int32
}

type ListLatestPinsWithCreatorRow struct {
	ID               uuid.UUID
	CreatorID        uuid.UUID
	MediaUrl         string
	MediaType        string
	Url              sql.NullString
	Title            string
	Description      sql.NullString
	OgImage          sql.NullString
	OgData           pqtype.NullRawMessage
	CreatedAt        time.Time
	CreatorIDRef     uuid.UUID
	CreatorNickname  string
	CreatorAvatarUrl sql.NullString
}

func (q *Queries) ListLatestPinsWithCreator(ctx context.Context, arg ListLatestPinsWithCreatorParams) ([]ListLatestPinsWithCreatorRow, error) {
	rows, err := q.db.QueryContext(ctx, listLatestPinsWithCreator,
		arg.Column1,
		pq.Array(arg.Column2),
		arg.Column3,
		arg.Column4,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestPinsWithCreatorRow
	for rows.Next() {
		var i ListLatestPinsWithCreatorRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.MediaUrl,
			&i.MediaType,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.OgImage,
			&i.OgData,
			&i.CreatedAt,
			&i.CreatorIDRef,
			&i.CreatorNickname,
			&i.CreatorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPinsByCreator = `-- name: ListPinsByCreator :many
SELECT
    p.id, p.creator_id, p.media_url, p.media_type, p.url, p.title, p.description,
    p.og_image, p.og_data, p.created_at,
    c.id AS creator_id_ref,
    c.nickname AS creator_nickname,
    c.avatar_url AS creator_avatar_url
FROM pins p
JOIN creators c ON c.id = p.creator_id
WHERE p.creator_id = $1
  AND ($2::varchar = '' OR p.media_type = $2)
  AND ($3::uuid[] IS NULL OR EXISTS (
    SELECT 1 FROM pin_tags pt WHERE pt.pin_id = p.id AND pt.tag_id = ANY($3::uuid[])
  ))
ORDER BY p.created_at DESC, p.id DESC
LIMIT $4 OFFSET $5
`

type ListPinsByCreatorParams struct {
	CreatorID uuid.UUID
	Column2   string
	Column3   []uuid.UUID
	Limit     int32
	Offset    int32
}

type ListPinsByCreatorRow struct {
	ID               uuid.UUID
	CreatorID        uuid.UUID
	MediaUrl         string
	MediaType        string
	Url              sql.NullString
	Title            string
	Description      sql.NullString
	OgImage          sql.NullString
	OgData           pqtype.NullRawMessage
	CreatedAt        time.Time
	CreatorIDRef     uuid.UUID
	CreatorNickname  string
	CreatorAvatarUrl sql.NullString
}

func (q *Queries) ListPinsByCreator(ctx context.Context, arg ListPinsByCreatorParams) ([]ListPinsByCreatorRow, error) {
	rows, err := q.db.QueryContext(ctx, listPinsByCreator,
		arg.CreatorID,
		arg.Column2,
		pq.Array(arg.Column3),
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPinsByCreatorRow
	for rows.Next() {
		var i ListPinsByCreatorRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.MediaUrl,
			&i.MediaType,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.OgImage,
			&i.OgData,
			&i.CreatedAt,
			&i.CreatorIDRef,
			&i.CreatorNickname,
			&i.CreatorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPinsWithCreator = `-- name: ListPinsWithCreator :many
SELECT
    p.id, p.creator_id, p.media_url, p.media_type, p.url, p.title, p.description,
    p.og_image, p.og_data, p.created_at,
    c.id AS creator_id_ref,
    c.nickname AS creator_nickname,
    c.avatar_url AS creator_avatar_url
FROM pins p
JOIN creators c ON c.id = p.creator_id
WHERE ($1::varchar = '' OR p.media_type = $1)
  AND ($2::uuid[] IS NULL OR EXISTS (
    SELECT 1 FROM pin_tags pt WHERE pt.pin_id = p.id AND pt.tag_id = ANY($2::uuid[])
  ))
ORDER BY p.created_at DESC, p.id DESC
LIMIT $3 OFFSET $4
`

type ListPinsWithCreatorParams struct {
	Column1 string
	Column2 []uuid.UUID
	Limit   int32
	Offset  int32
}

type ListPinsWithCreatorRow struct {
	ID               uuid.UUID
	CreatorID        uuid.UUID
	MediaUrl         string
	MediaType        string
	Url              sql.NullString
	Title            string
	Description      sql.NullString
	OgImage          sql.NullString
	OgData           pqtype.NullRawMessage
	CreatedAt        time.Time
	CreatorIDRef     uuid.UUID
	CreatorNickname  string
	CreatorAvatarUrl sql.NullString
}

func (q *Queries) ListPinsWithCreator(ctx context.Context, arg ListPinsWithCreatorParams) ([]ListPinsWithCreatorRow, error) {
	rows, err := q.db.QueryContext(ctx, listPinsWithCreator,
		arg.Column1,
		pq.Array(arg.Column2),
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPinsWithCreatorRow
	for rows.Next() {
		var i ListPinsWithCreatorRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.MediaUrl,
			&i.MediaType,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.OgImage,
			&i.OgData,
			&i.CreatedAt,
			&i.CreatorIDRef,
			&i.CreatorNickname,
			&i.CreatorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const relatedPins = `-- name: RelatedPins :many
SELECT
    p.id, p.creator_id, p.media_url, p.media_type, p.url, p.title, p.description,
    p.og_image, p.og_data, p.created_at,
    c.id AS creator_id_ref,
    c.nickname AS creator_nickname,
    c.avatar_url AS creator_avatar_url
FROM pins p
JOIN creators c ON c.id = p.creator_id
WHERE p.id != $1
  AND EXISTS (
    SELECT 1 FROM pin_tags pt
    WHERE pt.pin_id = p.id AND pt.tag_id = ANY($2::uuid[])
  )
ORDER BY
    CASE WHEN p.media_type = $3 THEN 0 ELSE 1 END,
    (SELECT count(*) FROM pin_tags pt WHERE pt.pin_id = p.id AND pt.tag_id = ANY($2::uuid[])) DESC,
    p.created_at DESC
LIMIT 10
`

type RelatedPinsParams struct {
	ID        uuid.UUID
	Column2   []uuid.UUID
	MediaType string
}

type RelatedPinsRow struct {
	ID               uuid.UUID
	CreatorID        uuid.UUID
	MediaUrl         string
	MediaType        string
	Url              sql.NullString
	Title            string
	Description      sql.NullString
	OgImage          sql.NullString
	OgData           pqtype.NullRawMessage
	CreatedAt        time.Time
	CreatorIDRef     uuid.UUID
	CreatorNickname  string
	CreatorAvatarUrl sql.NullString
}

func (q *Queries) RelatedPins(ctx context.Context, arg RelatedPinsParams) ([]RelatedPinsRow, error) {
	rows, err := q.db.QueryContext(ctx, relatedPins, arg.ID, pq.Array(arg.Column2), arg.MediaType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RelatedPinsRow
	for rows.Next() {
		var i RelatedPinsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.MediaUrl,
			&i.MediaType,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.OgImage,
			&i.OgData,
			&i.CreatedAt,
			&i.CreatorIDRef,
			&i.CreatorNickname,
			&i.CreatorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
