// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pins.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const countPins = `-- name: CountPins :one
SELECT count(*) FROM pins
WHERE ($1::varchar = '' OR field = $1)
  AND ($2::text[] IS NULL OR tags && $2::text[])
`

type CountPinsParams struct {
	Column1 string
	Column2 []string
}

func (q *Queries) CountPins(ctx context.Context, arg CountPinsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPins, arg.Column1, pq.Array(arg.Column2))
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPinsByCreatorFiltered = `-- name: CountPinsByCreatorFiltered :one
SELECT count(*) FROM pins
WHERE creator_id = $1
  AND ($2::varchar = '' OR field = $2)
  AND ($3::text[] IS NULL OR tags && $3::text[])
`

type CountPinsByCreatorFilteredParams struct {
	CreatorID uuid.UUID
	Column2   string
	Column3   []string
}

func (q *Queries) CountPinsByCreatorFiltered(ctx context.Context, arg CountPinsByCreatorFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPinsByCreatorFiltered, arg.CreatorID, arg.Column2, pq.Array(arg.Column3))
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPin = `-- name: CreatePin :one
INSERT INTO pins (creator_id, url, title, description, field, tags, og_image, og_data)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, creator_id, url, title, description, field, tags, og_image, og_data, created_at, pin_count
`

type CreatePinParams struct {
	CreatorID   uuid.UUID
	Url         string
	Title       string
	Description sql.NullString
	Field       string
	Tags        []string
	OgImage     sql.NullString
	OgData      pqtype.NullRawMessage
}

func (q *Queries) CreatePin(ctx context.Context, arg CreatePinParams) (Pin, error) {
	row := q.db.QueryRowContext(ctx, createPin,
		arg.CreatorID,
		arg.Url,
		arg.Title,
		arg.Description,
		arg.Field,
		pq.Array(arg.Tags),
		arg.OgImage,
		arg.OgData,
	)
	var i Pin
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.Field,
		pq.Array(&i.Tags),
		&i.OgImage,
		&i.OgData,
		&i.CreatedAt,
		&i.PinCount,
	)
	return i, err
}

const deletePin = `-- name: DeletePin :execrows
DELETE FROM pins
WHERE id = $1 AND creator_id = $2
`

type DeletePinParams struct {
	ID        uuid.UUID
	CreatorID uuid.UUID
}

func (q *Queries) DeletePin(ctx context.Context, arg DeletePinParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePin, arg.ID, arg.CreatorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPin = `-- name: GetPin :one
SELECT id, creator_id, url, title, description, field, tags, og_image, og_data, created_at, pin_count FROM pins
WHERE id = $1
`

func (q *Queries) GetPin(ctx context.Context, id uuid.UUID) (Pin, error) {
	row := q.db.QueryRowContext(ctx, getPin, id)
	var i Pin
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.Field,
		pq.Array(&i.Tags),
		&i.OgImage,
		&i.OgData,
		&i.CreatedAt,
		&i.PinCount,
	)
	return i, err
}

const getPinURL = `-- name: GetPinURL :one
SELECT url FROM pins WHERE id = $1
`

func (q *Queries) GetPinURL(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getPinURL, id)
	var url string
	err := row.Scan(&url)
	return url, err
}

const getPinWithCreator = `-- name: GetPinWithCreator :one
SELECT
    p.id, p.creator_id, p.url, p.title, p.description,
    p.field, p.tags, p.og_image, p.og_data, p.pin_count, p.created_at,
    c.id AS creator_id_ref,
    c.nickname AS creator_nickname,
    c.avatar_url AS creator_avatar_url
FROM pins p
JOIN creators c ON c.id = p.creator_id
WHERE p.id = $1
`

type GetPinWithCreatorRow struct {
	ID               uuid.UUID
	CreatorID        uuid.UUID
	Url              string
	Title            string
	Description      sql.NullString
	Field            string
	Tags             []string
	OgImage          sql.NullString
	OgData           pqtype.NullRawMessage
	PinCount         int32
	CreatedAt        time.Time
	CreatorIDRef     uuid.UUID
	CreatorNickname  string
	CreatorAvatarUrl sql.NullString
}

func (q *Queries) GetPinWithCreator(ctx context.Context, id uuid.UUID) (GetPinWithCreatorRow, error) {
	row := q.db.QueryRowContext(ctx, getPinWithCreator, id)
	var i GetPinWithCreatorRow
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.Field,
		pq.Array(&i.Tags),
		&i.OgImage,
		&i.OgData,
		&i.PinCount,
		&i.CreatedAt,
		&i.CreatorIDRef,
		&i.CreatorNickname,
		&i.CreatorAvatarUrl,
	)
	return i, err
}

const listLatestPinsWithCreator = `-- name: ListLatestPinsWithCreator :many
SELECT
    p.id, p.creator_id, p.url, p.title, p.description,
    p.field, p.tags, p.og_image, p.og_data, p.pin_count, p.created_at,
    c.id AS creator_id_ref,
    c.nickname AS creator_nickname,
    c.avatar_url AS creator_avatar_url
FROM pins p
JOIN creators c ON c.id = p.creator_id
WHERE ($1::varchar = '' OR p.field = $1)
  AND ($2::text[] IS NULL OR p.tags && $2::text[])
  AND (p.created_at < $3::timestamptz OR (p.created_at = $3::timestamptz AND p.id < $4::uuid))
ORDER BY p.created_at DESC, p.id DESC
LIMIT $5
`

type ListLatestPinsWithCreatorParams struct {
	Column1 string
	Column2 []string
	Column3 time.Time
	Column4 uuid.UUID
	Limit   int32
}

type ListLatestPinsWithCreatorRow struct {
	ID               uuid.UUID
	CreatorID        uuid.UUID
	Url              string
	Title            string
	Description      sql.NullString
	Field            string
	Tags             []string
	OgImage          sql.NullString
	OgData           pqtype.NullRawMessage
	PinCount         int32
	CreatedAt        time.Time
	CreatorIDRef     uuid.UUID
	CreatorNickname  string
	CreatorAvatarUrl sql.NullString
}

func (q *Queries) ListLatestPinsWithCreator(ctx context.Context, arg ListLatestPinsWithCreatorParams) ([]ListLatestPinsWithCreatorRow, error) {
	rows, err := q.db.QueryContext(ctx, listLatestPinsWithCreator,
		arg.Column1,
		pq.Array(arg.Column2),
		arg.Column3,
		arg.Column4,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestPinsWithCreatorRow
	for rows.Next() {
		var i ListLatestPinsWithCreatorRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.Field,
			pq.Array(&i.Tags),
			&i.OgImage,
			&i.OgData,
			&i.PinCount,
			&i.CreatedAt,
			&i.CreatorIDRef,
			&i.CreatorNickname,
			&i.CreatorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPinsByCreator = `-- name: ListPinsByCreator :many
SELECT
    p.id, p.creator_id, p.url, p.title, p.description,
    p.field, p.tags, p.og_image, p.og_data, p.pin_count, p.created_at,
    c.id AS creator_id_ref,
    c.nickname AS creator_nickname,
    c.avatar_url AS creator_avatar_url
FROM pins p
JOIN creators c ON c.id = p.creator_id
WHERE p.creator_id = $1
  AND ($2::varchar = '' OR p.field = $2)
  AND ($3::text[] IS NULL OR p.tags && $3::text[])
ORDER BY p.created_at DESC, p.id DESC
LIMIT $4 OFFSET $5
`

type ListPinsByCreatorParams struct {
	CreatorID uuid.UUID
	Column2   string
	Column3   []string
	Limit     int32
	Offset    int32
}

type ListPinsByCreatorRow struct {
	ID               uuid.UUID
	CreatorID        uuid.UUID
	Url              string
	Title            string
	Description      sql.NullString
	Field            string
	Tags             []string
	OgImage          sql.NullString
	OgData           pqtype.NullRawMessage
	PinCount         int32
	CreatedAt        time.Time
	CreatorIDRef     uuid.UUID
	CreatorNickname  string
	CreatorAvatarUrl sql.NullString
}

func (q *Queries) ListPinsByCreator(ctx context.Context, arg ListPinsByCreatorParams) ([]ListPinsByCreatorRow, error) {
	rows, err := q.db.QueryContext(ctx, listPinsByCreator,
		arg.CreatorID,
		arg.Column2,
		pq.Array(arg.Column3),
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPinsByCreatorRow
	for rows.Next() {
		var i ListPinsByCreatorRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.Field,
			pq.Array(&i.Tags),
			&i.OgImage,
			&i.OgData,
			&i.PinCount,
			&i.CreatedAt,
			&i.CreatorIDRef,
			&i.CreatorNickname,
			&i.CreatorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPinsWithCreator = `-- name: ListPinsWithCreator :many
SELECT
    p.id, p.creator_id, p.url, p.title, p.description,
    p.field, p.tags, p.og_image, p.og_data, p.pin_count, p.created_at,
    c.id AS creator_id_ref,
    c.nickname AS creator_nickname,
    c.avatar_url AS creator_avatar_url
FROM pins p
JOIN creators c ON c.id = p.creator_id
WHERE ($1::varchar = '' OR p.field = $1)
  AND ($2::text[] IS NULL OR p.tags && $2::text[])
ORDER BY p.created_at DESC, p.id DESC
LIMIT $3 OFFSET $4
`

type ListPinsWithCreatorParams struct {
	Column1 string
	Column2 []string
	Limit   int32
	Offset  int32
}

type ListPinsWithCreatorRow struct {
	ID               uuid.UUID
	CreatorID        uuid.UUID
	Url              string
	Title            string
	Description      sql.NullString
	Field            string
	Tags             []string
	OgImage          sql.NullString
	OgData           pqtype.NullRawMessage
	PinCount         int32
	CreatedAt        time.Time
	CreatorIDRef     uuid.UUID
	CreatorNickname  string
	CreatorAvatarUrl sql.NullString
}

func (q *Queries) ListPinsWithCreator(ctx context.Context, arg ListPinsWithCreatorParams) ([]ListPinsWithCreatorRow, error) {
	rows, err := q.db.QueryContext(ctx, listPinsWithCreator,
		arg.Column1,
		pq.Array(arg.Column2),
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPinsWithCreatorRow
	for rows.Next() {
		var i ListPinsWithCreatorRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.Field,
			pq.Array(&i.Tags),
			&i.OgImage,
			&i.OgData,
			&i.PinCount,
			&i.CreatedAt,
			&i.CreatorIDRef,
			&i.CreatorNickname,
			&i.CreatorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const relatedPins = `-- name: RelatedPins :many
SELECT
    p.id, p.creator_id, p.url, p.title, p.description,
    p.field, p.tags, p.og_image, p.og_data, p.pin_count, p.created_at,
    c.id AS creator_id_ref,
    c.nickname AS creator_nickname,
    c.avatar_url AS creator_avatar_url
FROM pins p
JOIN creators c ON c.id = p.creator_id
WHERE p.id != $1
  AND p.tags && $2::text[]
ORDER BY
    CASE WHEN p.field = $3 THEN 0 ELSE 1 END,
    array_length(p.tags & $2::text[], 1) DESC NULLS LAST,
    p.created_at DESC
LIMIT 10
`

type RelatedPinsParams struct {
	ID      uuid.UUID
	Column2 []string
	Field   string
}

type RelatedPinsRow struct {
	ID               uuid.UUID
	CreatorID        uuid.UUID
	Url              string
	Title            string
	Description      sql.NullString
	Field            string
	Tags             []string
	OgImage          sql.NullString
	OgData           pqtype.NullRawMessage
	PinCount         int32
	CreatedAt        time.Time
	CreatorIDRef     uuid.UUID
	CreatorNickname  string
	CreatorAvatarUrl sql.NullString
}

func (q *Queries) RelatedPins(ctx context.Context, arg RelatedPinsParams) ([]RelatedPinsRow, error) {
	rows, err := q.db.QueryContext(ctx, relatedPins, arg.ID, pq.Array(arg.Column2), arg.Field)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RelatedPinsRow
	for rows.Next() {
		var i RelatedPinsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.Field,
			pq.Array(&i.Tags),
			&i.OgImage,
			&i.OgData,
			&i.PinCount,
			&i.CreatedAt,
			&i.CreatorIDRef,
			&i.CreatorNickname,
			&i.CreatorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePinCountByURL = `-- name: UpdatePinCountByURL :exec
UPDATE pins SET pin_count = (
    SELECT COUNT(DISTINCT p2.creator_id) FROM pins p2 WHERE p2.url = pins.url
) WHERE pins.url = $1
`

func (q *Queries) UpdatePinCountByURL(ctx context.Context, url string) error {
	_, err := q.db.ExecContext(ctx, updatePinCountByURL, url)
	return err
}
