// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const searchBoardsByILIKE = `-- name: SearchBoardsByILIKE :many
SELECT b.id, b.creator_id, b.name, b.description, b.is_public, b.created_at, b.updated_at,
       c.nickname AS creator_nickname
FROM boards b
JOIN creators c ON c.id = b.creator_id
WHERE b.is_public = true AND b.name ILIKE '%' || $1 || '%'
ORDER BY b.created_at DESC, b.id DESC
LIMIT $2 OFFSET $3
`

type SearchBoardsByILIKEParams struct {
	Column1 sql.NullString
	Limit   int32
	Offset  int32
}

type SearchBoardsByILIKERow struct {
	ID              uuid.UUID
	CreatorID       uuid.UUID
	Name            string
	Description     sql.NullString
	IsPublic        bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CreatorNickname string
}

func (q *Queries) SearchBoardsByILIKE(ctx context.Context, arg SearchBoardsByILIKEParams) ([]SearchBoardsByILIKERow, error) {
	rows, err := q.db.QueryContext(ctx, searchBoardsByILIKE, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchBoardsByILIKERow
	for rows.Next() {
		var i SearchBoardsByILIKERow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Name,
			&i.Description,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorNickname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBoardsBySimilarity = `-- name: SearchBoardsBySimilarity :many
SELECT b.id, b.creator_id, b.name, b.description, b.is_public, b.created_at, b.updated_at,
       c.nickname AS creator_nickname
FROM boards b
JOIN creators c ON c.id = b.creator_id
WHERE b.is_public = true AND similarity(b.name, $1) > 0.1
ORDER BY similarity(b.name, $1) DESC, b.created_at DESC, b.id DESC
LIMIT $2 OFFSET $3
`

type SearchBoardsBySimilarityParams struct {
	Similarity string
	Limit      int32
	Offset     int32
}

type SearchBoardsBySimilarityRow struct {
	ID              uuid.UUID
	CreatorID       uuid.UUID
	Name            string
	Description     sql.NullString
	IsPublic        bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CreatorNickname string
}

func (q *Queries) SearchBoardsBySimilarity(ctx context.Context, arg SearchBoardsBySimilarityParams) ([]SearchBoardsBySimilarityRow, error) {
	rows, err := q.db.QueryContext(ctx, searchBoardsBySimilarity, arg.Similarity, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchBoardsBySimilarityRow
	for rows.Next() {
		var i SearchBoardsBySimilarityRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Name,
			&i.Description,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorNickname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCreatorsByILIKE = `-- name: SearchCreatorsByILIKE :many
SELECT id, nickname, avatar_url, created_at
FROM creators
WHERE nickname ILIKE '%' || $1 || '%'
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type SearchCreatorsByILIKEParams struct {
	Column1 sql.NullString
	Limit   int32
	Offset  int32
}

type SearchCreatorsByILIKERow struct {
	ID        uuid.UUID
	Nickname  string
	AvatarUrl sql.NullString
	CreatedAt time.Time
}

func (q *Queries) SearchCreatorsByILIKE(ctx context.Context, arg SearchCreatorsByILIKEParams) ([]SearchCreatorsByILIKERow, error) {
	rows, err := q.db.QueryContext(ctx, searchCreatorsByILIKE, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCreatorsByILIKERow
	for rows.Next() {
		var i SearchCreatorsByILIKERow
		if err := rows.Scan(
			&i.ID,
			&i.Nickname,
			&i.AvatarUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCreatorsBySimilarity = `-- name: SearchCreatorsBySimilarity :many
SELECT id, nickname, avatar_url, created_at
FROM creators
WHERE similarity(nickname, $1) > 0.1
ORDER BY similarity(nickname, $1) DESC, created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type SearchCreatorsBySimilarityParams struct {
	Similarity string
	Limit      int32
	Offset     int32
}

type SearchCreatorsBySimilarityRow struct {
	ID        uuid.UUID
	Nickname  string
	AvatarUrl sql.NullString
	CreatedAt time.Time
}

func (q *Queries) SearchCreatorsBySimilarity(ctx context.Context, arg SearchCreatorsBySimilarityParams) ([]SearchCreatorsBySimilarityRow, error) {
	rows, err := q.db.QueryContext(ctx, searchCreatorsBySimilarity, arg.Similarity, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCreatorsBySimilarityRow
	for rows.Next() {
		var i SearchCreatorsBySimilarityRow
		if err := rows.Scan(
			&i.ID,
			&i.Nickname,
			&i.AvatarUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPinsByILIKE = `-- name: SearchPinsByILIKE :many
SELECT
    p.id, p.creator_id, p.media_url, p.media_type, p.url, p.title, p.description,
    p.og_image, p.og_data, p.created_at,
    c.id AS creator_id_ref,
    c.nickname AS creator_nickname,
    c.avatar_url AS creator_avatar_url
FROM pins p
JOIN creators c ON c.id = p.creator_id
WHERE p.title ILIKE '%' || $1 || '%'
   OR EXISTS (
     SELECT 1 FROM pin_tags pt JOIN tags t ON t.id = pt.tag_id
     WHERE pt.pin_id = p.id AND t.name ILIKE '%' || $1 || '%'
   )
ORDER BY p.created_at DESC, p.id DESC
LIMIT $2 OFFSET $3
`

type SearchPinsByILIKEParams struct {
	Column1 sql.NullString
	Limit   int32
	Offset  int32
}

type SearchPinsByILIKERow struct {
	ID               uuid.UUID
	CreatorID        uuid.UUID
	MediaUrl         string
	MediaType        string
	Url              sql.NullString
	Title            string
	Description      sql.NullString
	OgImage          sql.NullString
	OgData           pqtype.NullRawMessage
	CreatedAt        time.Time
	CreatorIDRef     uuid.UUID
	CreatorNickname  string
	CreatorAvatarUrl sql.NullString
}

func (q *Queries) SearchPinsByILIKE(ctx context.Context, arg SearchPinsByILIKEParams) ([]SearchPinsByILIKERow, error) {
	rows, err := q.db.QueryContext(ctx, searchPinsByILIKE, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPinsByILIKERow
	for rows.Next() {
		var i SearchPinsByILIKERow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.MediaUrl,
			&i.MediaType,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.OgImage,
			&i.OgData,
			&i.CreatedAt,
			&i.CreatorIDRef,
			&i.CreatorNickname,
			&i.CreatorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPinsBySimilarity = `-- name: SearchPinsBySimilarity :many
SELECT
    p.id, p.creator_id, p.media_url, p.media_type, p.url, p.title, p.description,
    p.og_image, p.og_data, p.created_at,
    c.id AS creator_id_ref,
    c.nickname AS creator_nickname,
    c.avatar_url AS creator_avatar_url,
    (similarity(p.title, $1) +
      CASE WHEN EXISTS (
        SELECT 1 FROM pin_tags pt JOIN tags t ON t.id = pt.tag_id
        WHERE pt.pin_id = p.id AND t.name ILIKE '%' || $1 || '%'
      ) THEN 0.5 ELSE 0 END)::float4 AS score
FROM pins p
JOIN creators c ON c.id = p.creator_id
WHERE similarity(p.title, $1) > 0.1
   OR EXISTS (
     SELECT 1 FROM pin_tags pt JOIN tags t ON t.id = pt.tag_id
     WHERE pt.pin_id = p.id AND t.name ILIKE '%' || $1 || '%'
   )
ORDER BY score DESC, p.created_at DESC, p.id DESC
LIMIT $2 OFFSET $3
`

type SearchPinsBySimilarityParams struct {
	Similarity string
	Limit      int32
	Offset     int32
}

type SearchPinsBySimilarityRow struct {
	ID               uuid.UUID
	CreatorID        uuid.UUID
	MediaUrl         string
	MediaType        string
	Url              sql.NullString
	Title            string
	Description      sql.NullString
	OgImage          sql.NullString
	OgData           pqtype.NullRawMessage
	CreatedAt        time.Time
	CreatorIDRef     uuid.UUID
	CreatorNickname  string
	CreatorAvatarUrl sql.NullString
	Score            float32
}

func (q *Queries) SearchPinsBySimilarity(ctx context.Context, arg SearchPinsBySimilarityParams) ([]SearchPinsBySimilarityRow, error) {
	rows, err := q.db.QueryContext(ctx, searchPinsBySimilarity, arg.Similarity, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPinsBySimilarityRow
	for rows.Next() {
		var i SearchPinsBySimilarityRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.MediaUrl,
			&i.MediaType,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.OgImage,
			&i.OgData,
			&i.CreatedAt,
			&i.CreatorIDRef,
			&i.CreatorNickname,
			&i.CreatorAvatarUrl,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPinsILIKEWithTagFilter = `-- name: SearchPinsILIKEWithTagFilter :many
SELECT
    p.id, p.creator_id, p.media_url, p.media_type, p.url, p.title, p.description,
    p.og_image, p.og_data, p.created_at,
    c.id AS creator_id_ref,
    c.nickname AS creator_nickname,
    c.avatar_url AS creator_avatar_url
FROM pins p
JOIN creators c ON c.id = p.creator_id
WHERE (p.title ILIKE '%' || $1 || '%'
   OR EXISTS (
     SELECT 1 FROM pin_tags pt JOIN tags t ON t.id = pt.tag_id
     WHERE pt.pin_id = p.id AND t.name ILIKE '%' || $1 || '%'
   ))
  AND (SELECT COUNT(*) FROM pin_tags pt2
       WHERE pt2.pin_id = p.id AND pt2.tag_id = ANY($4::uuid[])) = array_length($4::uuid[], 1)
ORDER BY p.created_at DESC, p.id DESC
LIMIT $2 OFFSET $3
`

type SearchPinsILIKEWithTagFilterParams struct {
	Column1 sql.NullString
	Limit   int32
	Offset  int32
	Column4 []uuid.UUID
}

type SearchPinsILIKEWithTagFilterRow struct {
	ID               uuid.UUID
	CreatorID        uuid.UUID
	MediaUrl         string
	MediaType        string
	Url              sql.NullString
	Title            string
	Description      sql.NullString
	OgImage          sql.NullString
	OgData           pqtype.NullRawMessage
	CreatedAt        time.Time
	CreatorIDRef     uuid.UUID
	CreatorNickname  string
	CreatorAvatarUrl sql.NullString
}

func (q *Queries) SearchPinsILIKEWithTagFilter(ctx context.Context, arg SearchPinsILIKEWithTagFilterParams) ([]SearchPinsILIKEWithTagFilterRow, error) {
	rows, err := q.db.QueryContext(ctx, searchPinsILIKEWithTagFilter,
		arg.Column1,
		arg.Limit,
		arg.Offset,
		pq.Array(arg.Column4),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPinsILIKEWithTagFilterRow
	for rows.Next() {
		var i SearchPinsILIKEWithTagFilterRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.MediaUrl,
			&i.MediaType,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.OgImage,
			&i.OgData,
			&i.CreatedAt,
			&i.CreatorIDRef,
			&i.CreatorNickname,
			&i.CreatorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPinsWithTagFilter = `-- name: SearchPinsWithTagFilter :many
SELECT
    p.id, p.creator_id, p.media_url, p.media_type, p.url, p.title, p.description,
    p.og_image, p.og_data, p.created_at,
    c.id AS creator_id_ref,
    c.nickname AS creator_nickname,
    c.avatar_url AS creator_avatar_url,
    (similarity(p.title, $1) +
      CASE WHEN EXISTS (
        SELECT 1 FROM pin_tags pt JOIN tags t ON t.id = pt.tag_id
        WHERE pt.pin_id = p.id AND t.name ILIKE '%' || $1 || '%'
      ) THEN 0.5 ELSE 0 END)::float4 AS score
FROM pins p
JOIN creators c ON c.id = p.creator_id
WHERE (similarity(p.title, $1) > 0.1
   OR EXISTS (
     SELECT 1 FROM pin_tags pt JOIN tags t ON t.id = pt.tag_id
     WHERE pt.pin_id = p.id AND t.name ILIKE '%' || $1 || '%'
   ))
  AND (SELECT COUNT(*) FROM pin_tags pt2
       WHERE pt2.pin_id = p.id AND pt2.tag_id = ANY($4::uuid[])) = array_length($4::uuid[], 1)
ORDER BY score DESC, p.created_at DESC, p.id DESC
LIMIT $2 OFFSET $3
`

type SearchPinsWithTagFilterParams struct {
	Similarity string
	Limit      int32
	Offset     int32
	Column4    []uuid.UUID
}

type SearchPinsWithTagFilterRow struct {
	ID               uuid.UUID
	CreatorID        uuid.UUID
	MediaUrl         string
	MediaType        string
	Url              sql.NullString
	Title            string
	Description      sql.NullString
	OgImage          sql.NullString
	OgData           pqtype.NullRawMessage
	CreatedAt        time.Time
	CreatorIDRef     uuid.UUID
	CreatorNickname  string
	CreatorAvatarUrl sql.NullString
	Score            float32
}

func (q *Queries) SearchPinsWithTagFilter(ctx context.Context, arg SearchPinsWithTagFilterParams) ([]SearchPinsWithTagFilterRow, error) {
	rows, err := q.db.QueryContext(ctx, searchPinsWithTagFilter,
		arg.Similarity,
		arg.Limit,
		arg.Offset,
		pq.Array(arg.Column4),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPinsWithTagFilterRow
	for rows.Next() {
		var i SearchPinsWithTagFilterRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.MediaUrl,
			&i.MediaType,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.OgImage,
			&i.OgData,
			&i.CreatedAt,
			&i.CreatorIDRef,
			&i.CreatorNickname,
			&i.CreatorAvatarUrl,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTopTags = `-- name: SearchTopTags :many
SELECT t.id, t.name, t.slug, t.category, COUNT(*) AS count
FROM pin_tags pt
JOIN tags t ON t.id = pt.tag_id
WHERE pt.pin_id = ANY($1::uuid[])
GROUP BY t.id, t.name, t.slug, t.category
ORDER BY count DESC
LIMIT 10
`

type SearchTopTagsRow struct {
	ID       uuid.UUID
	Name     string
	Slug     string
	Category string
	Count    int64
}

func (q *Queries) SearchTopTags(ctx context.Context, dollar_1 []uuid.UUID) ([]SearchTopTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchTopTags, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTopTagsRow
	for rows.Next() {
		var i SearchTopTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Category,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
