// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getPopularTags = `-- name: GetPopularTags :many
SELECT t.id, t.name, t.slug, t.category, COUNT(*) AS pin_count
FROM pin_tags pt
JOIN tags t ON t.id = pt.tag_id
GROUP BY t.id, t.name, t.slug, t.category
ORDER BY pin_count DESC
LIMIT $1
`

type GetPopularTagsRow struct {
	ID       uuid.UUID
	Name     string
	Slug     string
	Category string
	PinCount int64
}

func (q *Queries) GetPopularTags(ctx context.Context, limit int32) ([]GetPopularTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPopularTags, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPopularTagsRow
	for rows.Next() {
		var i GetPopularTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Category,
			&i.PinCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsByIDs = `-- name: GetTagsByIDs :many
SELECT id, name, slug, category, display_order
FROM tags
WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetTagsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getTagsByIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Category,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsForPins = `-- name: GetTagsForPins :many
SELECT pt.pin_id, t.id, t.name, t.slug, t.category
FROM pin_tags pt
JOIN tags t ON t.id = pt.tag_id
WHERE pt.pin_id = ANY($1::uuid[])
ORDER BY t.category, t.display_order
`

type GetTagsForPinsRow struct {
	PinID    uuid.UUID
	ID       uuid.UUID
	Name     string
	Slug     string
	Category string
}

func (q *Queries) GetTagsForPins(ctx context.Context, dollar_1 []uuid.UUID) ([]GetTagsForPinsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTagsForPins, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTagsForPinsRow
	for rows.Next() {
		var i GetTagsForPinsRow
		if err := rows.Scan(
			&i.PinID,
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, name, slug, category, display_order
FROM tags
ORDER BY category, display_order
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Category,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByCategory = `-- name: ListTagsByCategory :many
SELECT id, name, slug, category, display_order
FROM tags
WHERE category = $1
ORDER BY display_order
`

func (q *Queries) ListTagsByCategory(ctx context.Context, category string) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Category,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTags = `-- name: SearchTags :many
SELECT id, name, slug, category, display_order
FROM tags
WHERE name ILIKE '%' || $1 || '%'
ORDER BY category, display_order
LIMIT 50
`

func (q *Queries) SearchTags(ctx context.Context, dollar_1 sql.NullString) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, searchTags, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Category,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
