version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/chungsanghwa/fugue
